window.ERAS=[
 {n:"L’Antiquité",d:"Magie officielle et magie interdite",items:[
  ["vers 1750 av. J.-C.","Le code d’Hammurabi","À Babylone, la deuxième loi du code prévoit déjà le cas d’une accusation de sorcellerie : l’accusé doit se jeter dans le fleuve. S’il survit, c’est l’accusateur qui est puni. C’est la plus ancienne loi connue sur le sujet."],
  ["VIIIᵉ s. av. J.-C.","Circé, Médée, Hécate","Homère et les poètes grecs installent les grandes figures de la magicienne : Circé et ses breuvages, Médée et ses onguents, Hécate, déesse des carrefours, qu’on invoque la nuit."],
  ["Vᵉ s. av. J.-C.","Les tablettes de liaison","Dans tout le monde grec, puis romain, on grave sur des lamelles de plomb des formules pour « lier » un rival, un amant ou un adversaire au procès. On en a retrouvé plus de 1 600, jetées dans des puits et des tombes."],
  ["451 av. J.-C.","La loi des Douze Tables","Le plus ancien texte de loi romain punit celui qui, par des incantations, attire chez lui la récolte de son voisin. La magie nuisible est un crime ; la magie de protection, elle, est partout."]]},
 {n:"Le Moyen Âge",d:"Quand l’Église ne croyait pas aux sorcières",items:[
  ["vers 906","Le Canon Episcopi","Ce texte de droit ecclésiastique déclare que les femmes qui croient chevaucher la nuit derrière la déesse Diane sont victimes d’illusions. Pendant des siècles, croire au vol des sorcières est officiellement une superstition."],
  ["1431","Jeanne d’Arc","Le procès de Rouen l’accuse d’abord, entre autres, de sorcellerie et de mandragore. Elle est finalement brûlée comme hérétique relapse. Elle sera réhabilitée en 1456 et canonisée en 1920."],
  ["1459–1460","La vauderie d’Arras","Dans le Nord de la France, des hommes et des femmes sont accusés de se rendre au sabbat en volant sur des bâtons enduits d’onguent. C’est l’un des premiers grands procès où apparaît l’image du sabbat diabolique."],
  ["1484","La bulle du pape Innocent VIII","La bulle « Summis desiderantes affectibus » reconnaît l’existence des sorcières en Allemagne et soutient les inquisiteurs qui les poursuivent. L’Église a changé de doctrine."],
  ["1486","Le Malleus Maleficarum","Heinrich Kramer publie « le Marteau des sorcières ». Imprimé et réimprimé, il devient le manuel de référence des juges. Il fait de la sorcellerie un crime surtout féminin."]]},
 {n:"Le temps des bûchers",d:"1560–1660, le cœur de la chasse",items:[
  ["1580","La Démonomanie de Jean Bodin","Le grand juriste français réclame une justice sans pitié contre les sorcières. Son livre est lu par les magistrats de toute l’Europe."],
  ["1590–1592","North Berwick","En Écosse, le roi Jacques VI est persuadé que des sorcières ont soulevé une tempête contre son navire. Plus de soixante-dix personnes sont accusées. Agnes Sampson, guérisseuse âgée, est torturée puis brûlée. Le roi publie en 1597 sa « Daemonologie », qui inspirera le « Macbeth » de Shakespeare."],
  ["1609","Le Labourd","Le juge Pierre de Lancre ravage le Pays basque français. Il décrit en détail l’« akelarre », le sabbat basque, dans un livre qui marque durablement l’imaginaire."],
  ["1610","Zugarramurdi et l’autodafé de Logroño","De l’autre côté de la frontière, l’Inquisition espagnole condamne les « sorcières » de Zugarramurdi : six sont brûlées vives. L’inquisiteur Alonso de Salazar Frías enquête ensuite sur place et conclut qu’il n’y a aucune preuve. Après son rapport, l’Inquisition espagnole cesse presque d’exécuter pour sorcellerie."],
  ["1612","Les sorcières de Pendle","Dans le Lancashire, dix personnes de deux familles rivales sont exécutées. Le témoignage central est celui d’une fillette de neuf ans, Jennet Device."],
  ["1626–1631","Würzburg et Bamberg","En Franconie, les princes-évêques organisent les chasses les plus meurtrières d’Europe. Des centaines de personnes sont brûlées, y compris des enfants, des prêtres et le maire de Bamberg, Johannes Junius, qui a laissé une lettre bouleversante à sa fille."],
  ["1634","Les possédées de Loudun","Des religieuses ursulines se disent possédées. Le curé Urbain Grandier est accusé de les avoir ensorcelées. Il est brûlé vif malgré l’absence de preuves."],
  ["1644–1647","Le « Witchfinder General »","Pendant la guerre civile anglaise, Matthew Hopkins parcourt l’Est de l’Angleterre et fait exécuter une centaine de personnes, en les empêchant de dormir pour obtenir des aveux."]]},
 {n:"La fin des bûchers",d:"Le doute, puis la loi",items:[
  ["1662","Isobel Gowdie","En Écosse, une jeune femme d’Auldearn fait, apparemment sans torture, des aveux extraordinaires : vols magiques, métamorphoses en lièvre, visite à la Reine des fées. Ses récits sont parmi les plus riches jamais recueillis."],
  ["1679–1682","L’affaire des poisons","À Paris, une enquête sur des empoisonnements révèle un réseau de devineresses et de messes noires qui touche la cour de Louis XIV. La Voisin est brûlée en place de Grève le 22 février 1680."],
  ["1682","L’édit de Louis XIV","L’édit royal requalifie la sorcellerie en « prétendue magie » : ce n’est plus un pacte avec le diable, mais une escroquerie ou un sacrilège. En France, les bûchers pour sorcellerie prennent fin."],
  ["1692","Salem","Dans le Massachusetts, des jeunes filles accusent leurs voisins. Dix-neuf personnes sont pendues, un homme meurt écrasé sous des pierres. En 1697, la colonie fait une journée de jeûne et de repentance."],
  ["1735","Le Witchcraft Act britannique","La loi ne punit plus la sorcellerie, mais le fait de prétendre la pratiquer pour escroquer. La sorcellerie n’est plus un crime réel, seulement une fraude."],
  ["1782","Anna Göldi","À Glaris, en Suisse, une servante accusée d’avoir ensorcelé la fille de son maître est décapitée. C’est l’une des dernières exécutions légales pour sorcellerie en Europe. Le canton l’a réhabilitée en 2008."]]},
 {n:"Le renouveau",d:"De la persécution à la religion",items:[
  ["1862","La Sorcière de Michelet","L’historien Jules Michelet fait de la sorcière une rebelle, une guérisseuse du peuple persécutée par l’Église et les seigneurs. Le livre transforme l’image de la sorcière en héroïne."],
  ["1899","Aradia de Leland","Le folkloriste américain Charles Godfrey Leland publie ce qu’il présente comme l’évangile secret des sorcières toscanes, la fille de Diane venue enseigner la magie aux pauvres. Son authenticité est débattue, mais le livre nourrit la Wicca."],
  ["1921","Margaret Murray","L’égyptologue britannique affirme dans « The Witch-Cult in Western Europe » que les sorcières étaient les fidèles d’une religion païenne survivante. La thèse est rejetée par les historiens, mais elle inspire tout le renouveau."],
  ["1944","Helen Duncan","Une médium écossaise est condamnée à neuf mois de prison en vertu du vieux Witchcraft Act de 1735. Churchill lui-même trouve l’affaire absurde. La loi est abrogée en 1951."],
  ["1954","Gerald Gardner et la Wicca","Trois ans après l’abrogation, Gerald Gardner publie « Witchcraft Today ». Il affirme avoir été initié dans un coven de la New Forest. La Wicca est née."],
  ["1957–1964","Doreen Valiente","La grande prêtresse de Gardner réécrit la « Charge de la Déesse », co-écrit la « Rune des sorcières » et popularise le Wiccan Rede : « Fais ce que tu veux, si tu ne nuis à personne. » On l’appelle la mère de la sorcellerie moderne."],
  ["1979","The Spiral Dance","L’Américaine Starhawk publie un livre qui mêle sorcellerie, féminisme et écologie. Il est vendu à des centaines de milliers d’exemplaires et façonne la sorcellerie américaine."],
  ["1988","La sorcière solitaire","Scott Cunningham publie « Wicca: A Guide for the Solitary Practitioner ». Pour la première fois, on peut devenir sorcière seule, sans coven ni initiation. C’est le livre de chevet de toute une génération."],
  ["1996","The Craft","Le film met en scène quatre lycéennes sorcières. Le réalisateur engage une prêtresse wiccane, Pat Devin, pour que les rituels soient crédibles. Le film déclenche une vague d’intérêt pour la sorcellerie chez les adolescents des années 1990."],
  ["2022","Les excuses de l’Écosse","La Première ministre écossaise présente les excuses officielles du gouvernement aux quelque 2 500 personnes exécutées pour sorcellerie dans le pays entre 1563 et 1736."]]}
];

window.FIGURES=[
 {g:"mythe",n:"Hécate",o:"Grèce antique",t:"Déesse des carrefours, de la lune noire et des fantômes, elle tient deux torches et est accompagnée de chiens. Médée était sa prêtresse. Les sorcières modernes en ont fait leur protectrice.",k:"Symboles : torche, clé, chien, carrefour"},
 {g:"mythe",n:"Circé",o:"Odyssée",t:"Fille du Soleil, elle change les compagnons d’Ulysse en porcs avec un breuvage. Ulysse lui résiste grâce au moly, une herbe donnée par Hermès. Il reste pourtant un an auprès d’elle.",k:"Symboles : coupe, baguette, porc"},
 {g:"mythe",n:"Médée",o:"Argonautes",t:"Princesse de Colchide, elle rend Jason invulnérable avec un onguent et endort le dragon de la Toison d’or. Trahie par lui, elle devient chez Euripide l’une des héroïnes les plus sombres du théâtre.",k:"Symboles : chaudron, dragon"},
 {g:"mythe",n:"Cerridwen",o:"Pays de Galles",t:"Elle prépare pendant un an et un jour un breuvage de sagesse dans son chaudron. Le jeune Gwion en avale trois gouttes par accident et devient le barde Taliesin. Son chaudron est l’ancêtre de celui des sorcières.",k:"Symboles : chaudron, truie blanche"},
 {g:"mythe",n:"Baba Yaga",o:"Monde slave",t:"Elle vit dans une isba montée sur des pattes de poule, voyage dans un mortier et efface ses traces avec un balai. Elle dévore les imprudents et récompense les courageux.",k:"Symboles : mortier, isba, crânes"},
 {g:"mythe",n:"Morgane",o:"Cycle arthurien",t:"Guérisseuse savante d’Avalon chez Geoffroy de Monmouth, puis ennemie de la cour d’Arthur dans les romans plus tardifs. C’est elle qui emporte le roi blessé vers l’île des pommes.",k:"Symboles : pomme, île, barque"},
 {g:"mythe",n:"La sorcière d’Endor",o:"Bible",t:"Le roi Saül, qui avait lui-même chassé les nécromanciens, se déguise pour la consulter. Elle fait apparaître l’esprit du prophète Samuel, qui lui annonce sa mort.",k:"Symboles : nécromancie, voile"},
 {g:"mythe",n:"La Befana",o:"Italie",t:"La nuit de l’Épiphanie, la vieille sorcière passe sur son balai de cheminée en cheminée. Elle laisse des friandises aux enfants sages et du charbon aux autres.",k:"Symboles : balai, bas, charbon"},
 {g:"histoire",n:"Agnes Sampson",o:"Écosse, † 1591",t:"Sage-femme et guérisseuse respectée, elle est interrogée par le roi Jacques VI lui-même lors des procès de North Berwick. Torturée, elle avoue avoir provoqué la tempête contre le navire royal. Elle est étranglée puis brûlée.",k:"Procès de North Berwick"},
 {g:"histoire",n:"Isobel Gowdie",o:"Écosse, 1662",t:"Ses quatre confessions, faites apparemment sans torture, décrivent des métamorphoses en lièvre, des vols sur des brins de paille et une visite à la Reine des fées. On ignore comment elle est morte.",k:"Aveux d’Auldearn"},
 {g:"histoire",n:"La Voisin",o:"Paris, † 1680",t:"Catherine Monvoisin, sage-femme et diseuse de bonne aventure, vendait horoscopes, philtres d’amour et, selon l’enquête, des poisons à la haute société. Elle est brûlée en place de Grève.",k:"Affaire des poisons"},
 {g:"histoire",n:"Tituba",o:"Salem, 1692",t:"Esclave au service du pasteur Samuel Parris, elle est l’une des trois premières accusées de Salem. Sa confession, sans doute obtenue sous la contrainte, lance la chasse. Elle survit et disparaît des archives.",k:"Procès de Salem"},
 {g:"histoire",n:"Mother Shipton",o:"Yorkshire, XVIᵉ s.",t:"Prophétesse légendaire née, dit-on, dans une grotte près de Knaresborough. Ses prophéties, publiées pour la première fois en 1641, ont été largement inventées ou enrichies plus tard. Sa grotte est l’une des plus anciennes attractions touristiques d’Angleterre.",k:"Prophéties"},
 {g:"histoire",n:"Anna Göldi",o:"Suisse, † 1782",t:"Servante accusée d’avoir fait cracher des épingles à la fille de son maître. Décapitée à Glaris, elle est réhabilitée en 2008. Un musée lui est consacré.",k:"Dernières exécutions"},
 {g:"histoire",n:"Marie Laveau",o:"La Nouvelle-Orléans, 1801–1881",t:"Coiffeuse, guérisseuse et prêtresse vaudou, elle était consultée par toutes les classes de la ville. Sa tombe au cimetière Saint-Louis n°1 est encore couverte d’offrandes.",k:"Reine du vaudou"},
 {g:"renouveau",n:"Gerald Gardner",o:"1884–1964",t:"Fonctionnaire colonial britannique passionné d’occultisme, il fonde la Wicca et publie « Witchcraft Today » en 1954. On lui doit la structure des covens, les degrés d’initiation et le Livre des Ombres.",k:"Fondateur de la Wicca"},
 {g:"renouveau",n:"Doreen Valiente",o:"1922–1999",t:"Poétesse et grande prêtresse, elle a donné à la Wicca ses plus beaux textes, dont la « Charge de la Déesse ». Elle a quitté Gardner en 1957 et continué seule à écrire et à enseigner.",k:"Mère de la sorcellerie moderne"},
 {g:"renouveau",n:"Starhawk",o:"née en 1951",t:"Sorcière et militante écologiste américaine, cofondatrice de la tradition Reclaiming. Son livre « The Spiral Dance » (1979) relie magie, féminisme et nature.",k:"The Spiral Dance"},
 {g:"renouveau",n:"Laurie Cabot",o:"née en 1933",t:"Installée à Salem, elle y ouvre l’une des premières boutiques de sorcellerie. Le gouverneur du Massachusetts la nomme en 1977 « sorcière officielle de Salem ».",k:"Sorcière de Salem"},
 {g:"renouveau",n:"Scott Cunningham",o:"1956–1993",t:"Auteur américain de livres simples et clairs sur les herbes, les cristaux et la pratique solitaire. Son guide de 1988 a ouvert la sorcellerie à des millions de personnes.",k:"La sorcière solitaire"}
];
