/* Pages ingrédients : k = mots-clés recherchés dans les sorts (sans accents, minuscules) */
window.INGREDIENTS=[
 {slug:"romarin",n:"Romarin",t:"Plante",lat:"Salvia rosmarinus",el:"Feu",pl:"Soleil",k:["romarin"],
  use:"Protection, purification, mémoire, amour fidèle.",
  h:["C’est l’herbe à tout faire de la sorcière européenne. Les étudiants grecs en portaient des couronnes pendant les examens pour la mémoire, et on en glissait dans les bouquets de mariée comme gage de fidélité. Au Moyen Âge, on en brûlait dans les chambres des malades pour purifier l’air.","En sorcellerie moderne, il remplace volontiers la sauge blanche pour les fumigations, et entre dans presque tous les sachets de protection."]},
 {slug:"lavande",n:"Lavande",t:"Plante",lat:"Lavandula angustifolia",el:"Air",pl:"Mercure",k:["lavande"],
  use:"Paix, sommeil, apaisement, amour doux, purification.",
  h:["Les Romains en parfumaient leurs bains, d’où son nom, du latin « lavare », laver. Les lavandières de Provence en mettaient dans le linge contre les mites.","C’est la plante des sorts de sommeil et de calme, et un ingrédient classique des oreillers à rêves et des bains rituels."]},
 {slug:"laurier",n:"Laurier",t:"Plante",lat:"Laurus nobilis",el:"Feu",pl:"Soleil",k:["laurier"],
  use:"Vœux, victoire, réussite, rêves prémonitoires, protection.",
  h:["Plante d’Apollon, le laurier couronnait les vainqueurs des jeux pythiques et les poètes, d’où le mot « lauréat ». La Pythie de Delphes, qui rendait les oracles, lui était associée.","Écrire un vœu sur une feuille de laurier puis la brûler est le plus simple et le plus populaire des sorts modernes."]},
 {slug:"sel",n:"Sel",t:"Minéral",lat:"Chlorure de sodium",el:"Terre",pl:"",k:["sel","sel noir","eau salee"],
  use:"Protection, purification, frontière, ancrage.",
  h:["Le sel conserve, donc il protège de la corruption. Dans presque toutes les traditions, il chasse le mal : on en jette par-dessus l’épaule quand on en renverse, on en met aux seuils, on en offre avec le pain aux nouveaux voisins.","C’est l’ingrédient de base du cercle, des bains de purification et du sel noir. Attention : il stérilise la terre, ne le jette jamais au jardin."]},
 {slug:"cannelle",n:"Cannelle",t:"Épice",lat:"Cinnamomum verum",el:"Feu",pl:"Soleil",k:["cannelle"],
  use:"Succès, argent rapide, chaleur, passion, protection.",
  h:["Épice précieuse de l’Antiquité, la cannelle valait plus cher que l’or à Rome. Les Égyptiens l’utilisaient dans l’embaumement et les parfums sacrés.","En sorcellerie moderne, elle accélère et réchauffe : on la souffle sur le seuil le premier du mois pour la prospérité, et on en roule les bougies des sorts d’amour et de réussite."]},
 {slug:"armoise",n:"Armoise",t:"Plante",lat:"Artemisia vulgaris",el:"Terre",pl:"Lune",k:["armoise"],
  use:"Rêves, divination, voyage, protection.",
  h:["Plante d’Artémis, déesse de la Lune, l’armoise était la grande herbe de la Saint-Jean : on en portait des ceintures en dansant autour des feux, puis on les jetait dans les flammes pour brûler les malheurs de l’année. Les voyageurs en glissaient dans leurs chaussures contre la fatigue.","C’est l’herbe des rêves et de la voyance : on en remplit les oreillers et on en lave les miroirs noirs."],
  warn:"Déconseillée pendant la grossesse et l’allaitement. À respirer ou manipuler, pas à consommer."},
 {slug:"rose",n:"Rose",t:"Plante",lat:"Rosa",el:"Eau",pl:"Vénus",k:["petales de rose","boutons de rose","eau de rose","roses","rosier"],
  use:"Amour, amour de soi, beauté, réconciliation, bénédiction.",
  h:["Fleur de Vénus et d’Aphrodite, la rose est le symbole universel de l’amour. Au Moyen Âge, elle devient aussi la fleur de la Vierge : le mot « rosaire » vient de là.","Pétales, boutons, eau de rose ou huile : elle entre dans tous les sorts d’amour et de glamour."]},
 {slug:"basilic",n:"Basilic",t:"Plante",lat:"Ocimum basilicum",el:"Feu",pl:"Mars",k:["basilic"],
  use:"Prospérité, harmonie du foyer, amour, protection.",
  h:["Son nom vient du grec « basilikos », royal. En Italie, un pot de basilic à la fenêtre signalait autrefois qu’une jeune femme était prête à recevoir un prétendant.","En sorcellerie, c’est une plante d’argent et de paix domestique : on en met dans les bocaux d’abondance et on en garde un pot près de la porte."]},
 {slug:"menthe",n:"Menthe",t:"Plante",lat:"Mentha",el:"Air",pl:"Mercure",k:["menthe"],
  use:"Argent, énergie, clarté, voyage, purification.",
  h:["Selon la mythologie grecque, la nymphe Minthé fut changée en plante par Perséphone jalouse. Les Romains en frottaient les tables pour accueillir leurs invités.","Fraîche et stimulante, elle sert aux sorts d’argent, de clarté mentale et d’études."]},
 {slug:"camomille",n:"Camomille",t:"Plante",lat:"Matricaria chamomilla",el:"Eau",pl:"Soleil",k:["camomille"],
  use:"Calme, sommeil, chance, argent, douceur.",
  h:["Les Égyptiens la consacraient au Soleil pour ses fleurs rondes et dorées. Dans les campagnes anglaises, on la plantait dans les allées : plus on la piétinait, plus elle poussait et parfumait l’air.","C’est la plante des sorts de sommeil et des porte-bonheur : les joueurs s’en frottaient les mains avant de jouer."]},
 {slug:"sauge",n:"Sauge officinale",t:"Plante",lat:"Salvia officinalis",el:"Air",pl:"Jupiter",k:["sauge"],
  use:"Sagesse, purification, longévité, protection.",
  h:["« Qui a de la sauge dans son jardin n’a pas besoin de médecin », disait un proverbe médiéval. Son nom vient du latin « salvare », sauver.","La sauge de nos jardins est une excellente plante de fumigation, sans poser les problèmes de surexploitation de la sauge blanche d’Amérique."]},
 {slug:"miel",n:"Miel",t:"Produit",lat:"",el:"Eau",pl:"Soleil",k:["miel"],
  use:"Douceur, amour, attraction, adoucir une relation.",
  h:["Nourriture des dieux dans de nombreuses mythologies, le miel était offert aux divinités et aux morts. Les abeilles, messagères entre les mondes, devaient être averties des décès dans les familles anglaises : c’est le « telling the bees ».","En magie, on « adoucit » avec le miel : pots de miel, offrandes, gâteaux des âmes."]},
 {slug:"pomme",n:"Pomme",t:"Fruit",lat:"Malus domestica",el:"Eau",pl:"Vénus",k:["pomme"],
  use:"Amour, divination, immortalité, offrande aux morts.",
  h:["Coupée à l’horizontale, la pomme révèle une étoile à cinq branches. Fruit d’Avalon, l’île des pommes où repose Arthur, et des pommes d’or des Hespérides, elle est liée à l’immortalité et à l’autre monde.","C’est le fruit de Samhain et de Mabon, et l’outil de nombreuses divinations d’amour."]},
 {slug:"citron",n:"Citron",t:"Fruit",lat:"Citrus limon",el:"Eau",pl:"Lune",k:["citron"],
  use:"Purification, absorption du négatif, clarté.",
  h:["Grand purificateur des traditions méditerranéennes et latino-américaines, le citron est utilisé contre le mauvais œil et dans les « limpias », les nettoyages spirituels.","Coupé et salé, il « boit » les tensions d’une pièce."]},
 {slug:"clou-de-girofle",n:"Clou de girofle",t:"Épice",lat:"Syzygium aromaticum",el:"Feu",pl:"Jupiter",k:["girofle"],
  use:"Protection, attraction, faire taire les ragots.",
  h:["Épice des Moluques, le clou de girofle a fait la fortune des marchands vénitiens puis hollandais. Les courtisans chinois en mâchaient pour avoir l’haleine fraîche devant l’empereur.","Piqué dans un citron ou une orange, il sert à la fois de protection et de parfum."]},
 {slug:"bougie",n:"Bougies",t:"Outil",lat:"",el:"Feu",pl:"",k:["bougie"],
  use:"Porter l’intention, par sa couleur et sa flamme.",
  h:["La flamme est l’élément le plus utilisé de toute la sorcellerie moderne. La couleur de la bougie porte l’intention : vert pour l’argent, rose pour l’amour, noir pour protéger et bannir, blanc pour tout.","On « habille » la bougie d’huile et d’herbes avant de l’allumer, et on observe sa flamme pour lire le résultat."]},
 {slug:"amethyste",n:"Améthyste",t:"Pierre",lat:"Quartz violet",el:"Eau",pl:"Jupiter",k:["amethyste"],
  use:"Sommeil, calme, intuition, protection contre les excès.",
  h:["Son nom vient du grec « amethystos », « qui n’est pas ivre » : les Grecs pensaient qu’elle protégeait de l’ivresse, et buvaient dans des coupes d’améthyste.","C’est la pierre des sorts de sommeil et d’apaisement. Elle pâlit au soleil : charge-la plutôt à la lune."]},
 {slug:"quartz-rose",n:"Quartz rose",t:"Pierre",lat:"Quartz",el:"Eau",pl:"Vénus",k:["quartz rose"],
  use:"Amour, amour de soi, réconciliation, douceur.",
  h:["Une légende grecque raconte qu’Aphrodite, en se blessant pour sauver Adonis, teinta de son sang un quartz blanc qui devint rose.","C’est la pierre de tous les sorts d’amour, et surtout d’amour de soi."]},
 {slug:"tourmaline-noire",n:"Tourmaline noire",t:"Pierre",lat:"Schorl",el:"Terre",pl:"Saturne",k:["tourmaline"],
  use:"Protection, ancrage, renvoi du négatif.",
  h:["Les pierres noires ont toujours servi à protéger. La tourmaline noire est devenue au XXᵉ siècle la grande pierre de protection de la sorcellerie moderne.","On la pose près de l’entrée, dans les bouteilles de sorcière ou dans les sachets de protection."]},
 {slug:"citrine",n:"Citrine",t:"Pierre",lat:"Quartz jaune",el:"Feu",pl:"Soleil",k:["citrine"],
  use:"Abondance, joie, réussite, confiance.",
  h:["Son nom vient du français « citron ». Surnommée « pierre du marchand », on la gardait dans les caisses pour attirer les clients.","C’est la pierre des bocaux d’abondance et des sorts de réussite."]},
 {slug:"cornaline",n:"Cornaline",t:"Pierre",lat:"Calcédoine",el:"Feu",pl:"Mars",k:["cornaline"],
  use:"Courage, créativité, élan, prise de parole.",
  h:["Portée par les soldats égyptiens et romains pour le courage, la cornaline servait aussi à graver les sceaux, car la cire ne colle pas dessus.","C’est la pierre des sorts de courage, d’entretien et de confiance."]},
 {slug:"obsidienne",n:"Obsidienne",t:"Pierre",lat:"Verre volcanique",el:"Feu",pl:"Saturne",k:["obsidienne"],
  use:"Vérité, miroir, coupure des liens, voyance.",
  h:["Verre né des volcans, l’obsidienne servait aux Aztèques à faire des miroirs sacrés, dédiés au dieu Tezcatlipoca, le « miroir fumant ». Le miroir de John Dee, astrologue d’Élisabeth Iʳᵉ, conservé au British Museum, est en obsidienne.","C’est la pierre des miroirs noirs et des sorts de lâcher-prise."]},
 {slug:"pierre-de-lune",n:"Pierre de lune",t:"Pierre",lat:"Feldspath",el:"Eau",pl:"Lune",k:["pierre de lune"],
  use:"Intuition, cycles, rêves, féminin.",
  h:["Ses reflets bleutés, qui bougent avec la lumière, faisaient croire aux Romains qu’elle était faite de rayons de lune solidifiés.","C’est la pierre de l’eau de lune et des sorts d’intuition."]},
 {slug:"quartz-clair",n:"Quartz clair",t:"Pierre",lat:"Cristal de roche",el:"Tous",pl:"Soleil",k:["quartz clair","un quartz","ou quartz","quartz)"],
  use:"Amplifier l’intention. Remplace toutes les autres pierres.",
  h:["Les Grecs pensaient que le cristal de roche était de la glace éternelle, gelée si fort qu’elle ne fondait plus : son nom vient de « krystallos », la glace. Les boules de cristal des voyantes sont taillées dans ce quartz.","En sorcellerie, c’est la pierre passe-partout : si tu n’en as qu’une, prends celle-là."]}
];
