window.SOURCES=[
 ["Chasse aux sorcières","https://fr.wikipedia.org/wiki/Chasse_aux_sorci%C3%A8res","Wikipédia"],
 ["Malleus Maleficarum","https://en.wikipedia.org/wiki/Malleus_Maleficarum","Wikipedia"],
 ["North Berwick witch trials","https://en.wikipedia.org/wiki/North_Berwick_witch_trials","Wikipedia"],
 ["Anna Göldi","https://en.wikipedia.org/wiki/Anna_G%C3%B6ldi","Wikipedia"],
 ["El auto de fe de Logroño de 1610","https://blogs.ua.es/brujeriainquisicion/2010/12/01/el-auto-de-fe-de-logrono-de-1610-y-las-brujas-de-zugarramurdi/","Université d’Alicante"],
 ["Affaire des poisons","https://fr.wikipedia.org/wiki/Affaire_des_poisons","Wikipédia"],
 ["22 février 1680, exécution de la Voisin","https://www.herodote.net/22_fevrier_1680-evenement-16800222.php","Herodote.net"],
 ["L’affaire des poisons","https://www.justice.gouv.fr/actualites/actualite/laffaire-poisons","Ministère de la Justice"],
 ["Petit Albert (grimoire)","https://fr.wikipedia.org/wiki/Petit_Albert_(grimoire)","Wikipédia"],
 ["Doreen Valiente","https://en.wikipedia.org/wiki/Doreen_Valiente","Wikipedia"],
 ["Charge of the Goddess: History and Variations","https://www.learnreligions.com/charge-of-the-goddess-history-and-variations-4151704","Learn Religions"],
 ["Where Do All Those Spells in The Craft Come From?","https://collider.com/the-craft-movie-wiccan-incantations/","Collider"],
 ["The Craft Inspired Witchcraft On and Off Screen","https://time.com/5904701/the-craft-legacy-witches/","TIME"],
 ["Roue de l’année","https://fr.wikipedia.org/wiki/Roue_de_l'ann%C3%A9e","Wikipédia"],
 ["Wheel of the Year: the 8 Sabbats","https://www.pagangrimoire.com/wheel-of-the-year/","The Pagan Grimoire"],
 ["Sabbats : la roue de l’année","https://auteldesbrumes.com/blog/blog-categorie/sabbats-roue-de-l-annee","Autel des Brumes"],
 ["Magical tools in Wicca","https://en.wikipedia.org/wiki/Magical_tools_in_Wicca","Wikipedia"],
 ["The 7 Must-Have Witchcraft Tools","https://www.pagangrimoire.com/witchcraft-tools/","The Pagan Grimoire"],
 ["Witch bottle","https://en.wikipedia.org/wiki/Witch_bottle","Wikipedia"],
 ["What Do We Mean By Magical Binding?","https://www.learnreligions.com/what-is-magical-binding-2561870","Learn Religions"],
 ["Self-Dedication Ritual for Solitary Pagans","https://www.learnreligions.com/self-dedication-ritual-2562868","Learn Religions"],
 ["Cakes and Ale in Pagan & Wiccan Ritual","https://www.learnreligions.com/ceremonial-magic-2561877","Learn Religions"],
 ["13 Esbat Rituals for a Full Moon","https://spells8.com/esbat-wiccan-ritual/","Spells8"],
 ["Sigil Making 101","https://spells8.com/sigil-making-101/","Spells8"],
 ["How to Make Black Salt","https://plentifulearth.com/spiritual-guidance/how-to-make-black-salt/","Plentiful Earth"],
 ["Moon Water: How to Make It","https://plentifulearth.com/spiritual-beginners/how-to-make-full-moon-water/","Plentiful Earth"],
 ["Candle Magic Flame Meanings","https://www.pagangrimoire.com/candle-signs-flame-meanings/","The Pagan Grimoire"],
 ["Candle Color Meanings & Magick","https://moonfallmetaphysical.com/s/stories/candle-magic-meaning-colors/","Moonfall Metaphysical"],
 ["Tasseography: How to Read Your Tea Leaves","https://www.harney.com/blogs/news/tasseography","Harney & Sons"],
 ["Drawing down the Moon (ritual)","https://en.wikipedia.org/wiki/Drawing_down_the_Moon_(ritual)","Wikipedia"],
 ["Four thieves vinegar","https://en.wikipedia.org/wiki/Four_thieves_vinegar","Wikipedia"],
 ["Magical Dolls: A History of Poppets","http://www.badwitch.co.uk/2018/11/magical-dolls-history-of-poppets-effigy.html","A Bad Witch’s Blog"]
];
