window.CHAPTERS=[
 {id:"protection",r:"I",n:"Protection",c:"#5b6f8a",i:"Les plus anciens sorts de l’humanité servent à garder le seuil : la maison, le corps, la route. On les lance de préférence en lune décroissante ou le samedi, jour de Saturne, gardien des limites."},
 {id:"purification",r:"II",n:"Purification & bannissement",c:"#6f7f6a",i:"Avant d’attirer quoi que ce soit, on fait place nette. Ces sorts lavent un lieu, une personne ou une situation, et éloignent ce qui n’a plus à rester."},
 {id:"liaison",r:"III",n:"Liens & liaisons",c:"#6b4f7a",i:"La magie de liaison est aussi vieille que les tablettes de plomb grecques, les katadesmoi. On lie pour empêcher de nuire, pas pour contraindre. C’est le chapitre qui demande le plus de réflexion éthique."},
 {id:"amour",r:"IV",n:"Amour & amitié",c:"#a0566a",i:"La tradition moderne est claire : on ne vise jamais une personne précise pour forcer ses sentiments. On ouvre son cœur, on attire ce qui nous correspond, on répare ce qui a été abîmé."},
 {id:"prosperite",r:"V",n:"Prospérité & chance",c:"#5e8a55",i:"L’argent, le travail, les occasions. Ces sorts se font en lune croissante, le jeudi (Jupiter) ou le dimanche (Soleil), et s’accompagnent toujours d’une action concrète dans le monde réel."},
 {id:"bienetre",r:"VI",n:"Soin & bien-être",c:"#4f8a86",i:"Les anciennes guérisseuses mêlaient plantes, prières et gestes. Ces sorts accompagnent le repos et le moral. Ils ne remplacent jamais un médecin."},
 {id:"reves",r:"VII",n:"Rêves & sommeil",c:"#4a5c8f",i:"La nuit est le territoire de la Lune. On y cherche le repos, des rêves clairs, parfois des réponses."},
 {id:"divination",r:"VIII",n:"Divination",c:"#8a6a3a",i:"Voir ce qui est caché : dans la cire, l’eau noire, les feuilles de thé ou la flamme. La divination n’annonce pas un destin figé, elle éclaire une question."},
 {id:"glamour",r:"IX",n:"Glamour & confiance",c:"#9a5a8a",i:"Le glamour, au sens ancien, c’est un charme qui change la façon dont les autres nous perçoivent. Aujourd’hui, on s’en sert surtout pour changer la façon dont on se voit."},
 {id:"elements",r:"X",n:"Éléments & saisons",c:"#8a5a3a",i:"Terre, Air, Feu, Eau : les quatre éléments de la philosophie grecque forment la grammaire de la sorcellerie. Ces sorts travaillent directement avec eux."},
 {id:"lune",r:"XI",n:"Magie lunaire",c:"#7a7a90",i:"Chaque phase a sa couleur : on sème à la nouvelle lune, on fait grandir en croissante, on célèbre à la pleine, on coupe en décroissante."},
 {id:"sceaux",r:"XII",n:"Sceaux & écritures",c:"#7a3a3a",i:"Écrire, c’est fixer. Des carrés magiques de l’Antiquité aux sigils du XXᵉ siècle, ce chapitre rassemble la magie des signes."}
];

window.SPELLS=[
/* ===================== I. PROTECTION ===================== */
{id:"bouteille",ch:"protection",n:"La bouteille de sorcière",sub:"Piège à mauvais sorts, enterré sous le seuil",lvl:2,moon:"Décroissante ou noire",day:"Samedi",dur:"45 min",
 ing:["un bocal ou une petite bouteille en verre avec couvercle","des clous rouillés, des épingles, des aiguilles","des éclats de verre ou de miroir (manipule-les avec des gants)","du gros sel","du romarin séché","du vinaigre","trois de tes cheveux et une rognure d’ongle","une bougie noire"],
 steps:["Trace le cercle et allume la bougie noire. Pose tous les ingrédients devant toi.","Mets d’abord les objets pointus dans la bouteille, un par un, en disant pour chacun : « Toi, tu perces ce qui vient me blesser. »","Ajoute le sel et le romarin, qui purifient et gardent.","Ajoute tes cheveux et ton ongle : ils font de la bouteille ton double, celui qui recevra les coups à ta place.","Remplis de vinaigre (autrefois, on utilisait de l’urine), en récitant l’incantation.","Ferme et scelle le couvercle avec la cire de la bougie noire.","Enterre la bouteille près de la porte d’entrée, sous une dalle ou dans un pot de terre à l’entrée. Elle ne doit jamais être ouverte ni cassée."],
 inc:"Pointe et clou, sel et vinaigre,\nce qui vient m’atteindre ici s’enferre.\nPrisonnier du verre et de la terre,\nle mal ne passe pas ma barrière.",
 var:["En appartement : cache-la au fond d’un placard près de l’entrée ou dans une jardinière du balcon.","Version douce : remplace les objets pointus par des épines de rosier et le vinaigre par de l’eau de mer."],
 note:"Les archéologues ont retrouvé plus de deux cents bouteilles de sorcière en Angleterre, surtout en East Anglia. La plus ancienne mention écrite date de 1681. Au XVIIᵉ siècle, on utilisait des cruches en grès ornées d’un visage barbu, les « Bellarmines ». Une bouteille encore scellée, découverte à Greenwich en 2004, contenait des clous tordus, une épingle, des cheveux et de l’urine.",
 after:"On ne défait pas une bouteille de sorcière. Si tu déménages, fais-en une nouvelle et laisse l’ancienne en place.",
 m:"Le sort le plus documenté de toute l’archéologie."},

{id:"selnoir",ch:"protection",n:"Le cercle de sel noir",sub:"Une frontière que rien ne franchit",lvl:1,moon:"Décroissante",day:"Samedi",dur:"30 min",
 ing:["2 mesures de gros sel","1 mesure de cendres de bois, de charbon végétal en poudre ou de poivre noir moulu","un mortier et un pilon","un bocal en verre"],
 steps:["Pile les cendres ou le charbon jusqu’à obtenir une poudre très fine.","Ajoute le sel, puis mélange au pilon dans le sens inverse des aiguilles d’une montre : c’est le sens qui éloigne.","Pendant que tu tournes, répète l’incantation jusqu’à ce que le sel soit uniformément noir.","Conserve le sel noir dans un bocal fermé, étiqueté, loin de la cuisine.","Pour protéger la maison, verse un mince trait de sel noir sur le rebord de chaque fenêtre et devant la porte d’entrée, côté extérieur.","Pour un rituel, trace un cercle de sel noir autour de toi avant de commencer."],
 inc:"Sel de la mer et cendre du feu,\nnoir est le trait, fermé le lieu.\nCe qui me veut du mal, recule,\nici s’arrête ta ruse.",
 var:["Ajoute des coquilles d’œuf pilées (la coquille protège le germe) ou des herbes protectrices brûlées : romarin, laurier, sauge.","Pour éloigner un visiteur indésirable, la tradition veut qu’on jette une pincée de sel noir derrière lui après son départ."],
 note:"Le sel noir vient du hoodoo, la magie populaire afro-américaine du Sud des États-Unis. On y noircissait le sel avec de la limaille de fer. Il est passé ensuite dans la sorcellerie moderne. Attention, il ne se mange pas : ce n’est pas le « kala namak » de la cuisine indienne.",
 after:"Balaie le sel usé vers l’extérieur et jette-le à la poubelle ou dans l’eau courante, jamais sur la terre du jardin : le sel stérilise le sol.",
 m:"À ne pas confondre avec le sel noir culinaire !"},

{id:"miroir",ch:"protection",n:"Le miroir renvoyeur",sub:"Rendre à l’expéditeur ce qui vous a été envoyé",lvl:2,moon:"Pleine ou décroissante",day:"Mardi ou samedi",dur:"20 min + 7 jours",
 ing:["un petit miroir de poche","une bougie noire et une blanche","du sel noir ou du gros sel","une boîte en carton ou en bois"],
 steps:["Allume la bougie blanche à gauche, pour toi, et la noire à droite, pour ce qui te nuit.","Tiens le miroir face vers l’extérieur, contre ta poitrine. Imagine une surface d’argent qui recouvre tout ton corps.","Récite l’incantation trois fois en tournant lentement sur toi-même.","Pose le miroir face vers le haut dans la boîte, sur un lit de sel, et referme.","Garde la boîte près de l’entrée pendant sept jours. Le septième jour, éteins les bougies pour de bon et range la boîte."],
 inc:"Miroir, miroir, sois mon bouclier,\nce qu’on m’envoie, renvoie-le entier.\nNi plus, ni moins, ni haine, ni rage :\nque chacun reçoive son propre ouvrage.",
 var:["Version portative : colle un petit miroir rond à l’intérieur de ton sac, face vers l’extérieur.","En Chine, le miroir bagua au-dessus des portes a la même fonction."],
 note:"Le miroir qui renvoie le mauvais œil existe dans presque toutes les cultures, du bagua chinois aux petits miroirs cousus sur les vêtements en Inde et en Asie centrale. Le principe est éthique : on ne crée rien de mauvais, on renvoie seulement ce qu’on a reçu.",
 after:"Si la situation est réglée, nettoie le miroir à l’eau salée et remets-le en usage ordinaire.",
 m:"On ne crée rien, on renvoie."},

{id:"seuil",ch:"protection",n:"La garde du seuil",sub:"Fer, sel et romarin sur la porte",lvl:1,moon:"Toutes phases",day:"Samedi",dur:"20 min",
 ing:["un clou en fer ou un fer à cheval","un bol d’eau salée","un brin de romarin frais","une craie blanche (facultatif)"],
 steps:["Nettoie le pas de porte et le seuil à l’eau salée, avec le brin de romarin qui sert de goupillon.","Trace à l’eau salée un pentagramme invisible sur la porte, du côté extérieur, en commençant par la pointe du haut.","Plante le clou au-dessus de la porte, à l’intérieur, ou accroche le fer à cheval pointes vers le haut pour que la chance ne s’écoule pas.","Glisse le brin de romarin au-dessus du cadre ou sous le paillasson.","Récite l’incantation en touchant les deux montants de la porte."],
 inc:"Fer qui ne plie, sel qui ne ment,\ngardez ma porte du couchant au levant.\nEntre l’ami, passe le voisin,\nrestent dehors le mal et le malin.",
 var:["Dans les campagnes françaises, on clouait parfois une chouette ou un chardon sur la porte des granges. Un bouquet de chardon séché fait aujourd’hui une belle alternative.","Renouvelle le romarin à chaque saison."],
 note:"Le fer est redouté des fées et des esprits dans le folklore européen, d’où le fer à cheval porte-bonheur. Le sort mêle trois protections très anciennes : le fer, le sel et une plante aromatique.",
 after:"Le romarin fané se brûle ou se composte.",
 m:"Fer à cheval : pointes en haut !"},

{id:"voyageur",ch:"protection",n:"Le sachet du voyageur",sub:"À porter sur soi sur la route",lvl:1,moon:"Croissante",day:"Mercredi (Mercure, patron des voyageurs)",dur:"15 min",
 ing:["un carré de tissu bleu ou blanc de 10 cm","une pincée de sel","de l’armoise séchée","du romarin","une petite pierre : œil-de-tigre, quartz ou turquoise","un ruban ou une cordelette"],
 steps:["Pose le tissu devant toi et visualise ton trajet, du départ à l’arrivée.","Dépose le sel au centre : « Pour la route sûre. »","Ajoute l’armoise : « Pour les pieds infatigables. »","Ajoute le romarin : « Pour le retour. »","Pose la pierre au milieu, puis ferme le sachet par trois nœuds, un pour chaque vers de l’incantation.","Souffle dessus avant chaque départ."],
 inc:"Sur la route et sous le ciel,\ngarde-moi sauf, garde-moi fidèle.\nQue je parte et que je revienne,\nque rien de mal ne me retienne.",
 var:["Pour la voiture : glisse-le dans la boîte à gants.","Au Moyen Âge, les pèlerins glissaient une feuille d’armoise dans leurs chaussures contre la fatigue."],
 note:"L’armoise, Artemisia vulgaris, porte le nom d’Artémis. Pline l’Ancien rapporte déjà qu’un voyageur qui la porte ne sent pas la fatigue.",
 after:"Renouvelle le sachet chaque année, ou après un long voyage. Enterre les anciennes herbes.",
 m:"Mercure veille sur les routes."},

/* ===================== II. PURIFICATION ===================== */
{id:"fumigation",ch:"purification",n:"La fumigation des quatre coins",sub:"Nettoyer une maison par la fumée",lvl:1,moon:"Décroissante",day:"Samedi ou dimanche",dur:"45 min",
 ing:["un fagot de romarin, laurier, thym ou lavande séchés, liés avec du fil de coton","une coupelle résistante à la chaleur et un peu de sable","une plume (facultatif)","une bougie blanche"],
 steps:["Fais le ménage, désencombre et ouvre toutes les fenêtres : la fumée doit pouvoir sortir.","Allume la bougie blanche au centre de la maison. Allume le fagot à sa flamme, puis souffle pour ne garder que la fumée.","Pars de la porte d’entrée et tourne dans la maison dans le sens inverse des aiguilles d’une montre, pièce par pièce.","Insiste sur les coins, derrière les portes, sous les lits et dans les placards : c’est là que l’énergie stagne. Pousse la fumée avec la plume ou la main.","À chaque pièce, récite l’incantation.","Termine à la porte d’entrée, que tu refermes. Écrase le fagot dans le sable."],
 inc:"Fumée d’herbe, souffle du feu,\nemporte tout ce qui pèse en ces lieux.\nPar la fenêtre, par la porte,\nque le vent au loin l’emporte.",
 var:["Sans fumée (enfants, animaux, asthme) : un vaporisateur d’eau, de sel et de quelques gouttes d’huile essentielle de romarin.","Après la fumigation, fais « entrer » le bon en faisant mijoter cannelle, écorces d’orange et clous de girofle."],
 note:"La fumigation est présente partout, de l’encens des temples antiques au genévrier que les Écossais faisaient brûler au Nouvel An (le « saining »). La sauge blanche, souvent vendue pour cela, est une plante sacrée de peuples autochtones de Californie et elle est surexploitée. Les herbes d’Europe font tout aussi bien l’affaire.",
 after:"Les cendres s’enterrent au pied d’un arbre, loin de la maison.",
 warn:"Ne laisse jamais un fagot fumant sans surveillance. Aère toujours bien.",
 m:"Sens inverse des aiguilles : on chasse."},

{id:"bainsel",ch:"purification",n:"Le bain de sel et d’hysope",sub:"Se laver d’une journée ou d’une rencontre",lvl:1,moon:"Décroissante",day:"Lundi",dur:"30 min",
 ing:["une poignée de gros sel ou de sel d’Epsom","une infusion forte d’hysope, de romarin ou de thym (une poignée dans un litre d’eau bouillante)","une bougie blanche","un verre d’eau fraîche à boire"],
 steps:["Prépare l’infusion et laisse-la tiédir pendant que la baignoire se remplit (une bassine pour les pieds convient aussi).","Verse le sel en disant : « Sel, défais. » Verse l’infusion filtrée en disant : « Herbe, lave. »","Allume la bougie et éteins la lumière.","Entre dans l’eau et immerge-toi entièrement, trois fois si possible.","Reste dix minutes en imaginant que tout ce qui t’a collé à la peau se dissout dans l’eau.","Au moment de vider la baignoire, reste dedans et regarde l’eau partir en récitant l’incantation. Sors seulement quand elle est vide.","Bois le verre d’eau fraîche."],
 inc:"Ce qui n’est pas à moi, je le rends,\nque l’eau l’emporte vers l’océan.\nJe sors d’ici léger et neuf,\ncomme un poussin qui sort de l’œuf.",
 var:["Sous la douche : frotte-toi de haut en bas avec du gros sel mélangé à un peu d’huile d’olive, puis rince.","Dans la Bible, l’hysope sert à purifier : « Purifie-moi avec l’hysope » (Psaume 51)."],
 note:"Le bain rituel se retrouve dans toutes les traditions, du mikvé juif aux « bains de démarrage » des traditions afro-caribéennes. La consigne de se laver du haut vers le bas pour éloigner, et du bas vers le haut pour attirer, vient de la magie populaire américaine.",
 after:"Aucun reste à jeter, l’eau est partie.",
 m:"Du haut vers le bas pour éloigner."},

{id:"citron",ch:"purification",n:"Le citron absorbant",sub:"Éponger les tensions d’une pièce",lvl:1,moon:"Décroissante",day:"Samedi",dur:"5 min + 7 jours",
 ing:["un citron","du gros sel","neuf clous de girofle","une soucoupe"],
 steps:["Coupe le citron en quatre sans séparer les quartiers à la base.","Remplis l’intérieur de gros sel.","Pique neuf clous de girofle dans l’écorce en récitant l’incantation, un vers par clou, et recommence.","Pose-le sur la soucoupe dans la pièce où ont eu lieu les disputes, ou sous le lit.","Laisse-le sept jours. S’il noircit ou moisit vite, c’est qu’il a beaucoup absorbé : recommence avec un nouveau citron."],
 inc:"Citron amer, bois la colère,\nsel qui ronge, prends la misère.\nClou de girofle, tiens-la serrée,\nque cette maison soit apaisée.",
 var:["Au bureau, un demi-citron salé sur une soucoupe fait l’affaire.","Dans la tradition méditerranéenne, on coupe aussi un citron en croix contre le mauvais œil."],
 note:"Le citron est un grand purificateur des magies méditerranéenne et latino-américaine (la « limpia »). Son acidité, réelle, en fait aussi un désodorisant.",
 after:"Jette le citron hors de la maison, idéalement dans une poubelle à l’extérieur, sans le toucher à mains nues.",
 m:"S’il noircit vite, recommence."},

{id:"bannissement",ch:"purification",n:"La bougie noire du bannissement",sub:"Couper une habitude, une influence, une peur",lvl:2,moon:"Décroissante, dernier quartier idéalement",day:"Samedi",dur:"1 h",
 ing:["une bougie noire (une chauffe-plat noire suffit)","un papier et un crayon","une aiguille ou un cure-dent","du poivre noir et du sel","une coupelle résistante à la chaleur"],
 steps:["Écris sur le papier ce que tu veux bannir, en un seul mot ou une seule phrase : « la peur de parler en public », « ma procrastination ».","Grave ce même mot sur la bougie avec l’aiguille, du haut vers le bas.","Enduis-la d’un peu d’huile, là aussi du haut vers le bas, puis roule-la dans le poivre et le sel.","Allume-la. Lis le papier à voix haute, puis récite l’incantation.","Brûle le papier à la flamme de la bougie, au-dessus de la coupelle.","Laisse la bougie se consumer entièrement, sous surveillance."],
 inc:"Ce qui me ronge, je te nomme,\net te nommant je te consume.\nFlamme noire, emporte-le loin,\nqu’il ne revienne plus demain.",
 var:["Si le sort concerne une personne, écris ce qu’elle te fait, jamais son nom. On bannit l’influence, pas l’être humain.","Pour une habitude, recommence neuf soirs de suite avec une chauffe-plat."],
 note:"Le noir n’est pas la couleur du mal en sorcellerie moderne. C’est la couleur qui absorbe, celle de Saturne et des limites.",
 after:"Les restes de cire et les cendres se jettent à un carrefour ou dans une poubelle éloignée de la maison. Ne reviens pas dessus.",
 m:"On bannit une influence, jamais une personne."},

{id:"lettre",ch:"purification",n:"La lettre à la rivière",sub:"Laisser partir une peine",lvl:1,moon:"Décroissante",day:"Lundi",dur:"1 h",
 ing:["du papier sans produit chimique (papier kraft, papier de riz ou papier hydrosoluble)","un crayon","une fleur ou une poignée de pétales"],
 steps:["Écris une lettre à ce qui te fait souffrir : une rupture, un deuil, une rancune. Écris tout, sans te relire.","Plie la lettre en l’éloignant de toi, trois fois.","Va jusqu’à une rivière, un ruisseau ou la mer. L’eau doit couler et s’éloigner.","Déchire la lettre en tout petits morceaux et confie-les au courant avec les pétales.","Récite l’incantation puis tourne le dos à l’eau. Pars sans te retourner."],
 inc:"Eau qui passe, eau qui va,\nprends ce que je ne garde pas.\nJusqu’à la mer, jusqu’à l’oubli,\nma peine s’en va, et je souris.",
 var:["En ville : laisse les morceaux se dissoudre dans un bol d’eau, puis verse l’eau dans l’évier en laissant couler le robinet.","Pour un deuil, garde un seul pétale en souvenir."],
 note:"Confier ses maux à l’eau courante est un geste très ancien. Au Japon, lors du Nagashi-bina, on met à l’eau des poupées de papier qui emportent les malheurs.",
 after:"Rien ne reste. Choisis bien un papier qui se décompose.",
 m:"Ne te retourne pas."},

/* ===================== III. LIAISON ===================== */
{id:"cordon",ch:"liaison",n:"Le cordon qui lie",sub:"Empêcher quelqu’un de nuire",lvl:3,moon:"Décroissante ou noire",day:"Samedi",dur:"1 h",
 ing:["une cordelette noire d’environ un mètre","une bougie noire et une blanche","un papier avec une description de la personne (ou son nom si la situation est grave)","une petite branche ou une poupée de tissu sans visage","du sel"],
 steps:["Trace le cercle de sel. Allume la bougie blanche pour toi et la noire pour la situation.","Sur le papier, écris précisément ce que tu veux empêcher : « Que X ne puisse plus me harceler », « Que X ne fasse plus de mal à personne ».","Enroule le papier autour de la branche ou glisse-le dans la poupée.","Enroule la cordelette autour, en partant du bas vers le haut, en répétant l’incantation.","Termine par neuf nœuds serrés, un par vers et un pour sceller.","Enveloppe le tout dans un tissu noir et range-le dans un endroit sombre, ou enterre-le loin de chez toi."],
 inc:"Je te lie, je ne te blesse,\nje retiens ta main qui presse.\nTu ne peux plus faire de mal,\nni à moi, ni à quiconque, c’est égal.\nPar le nœud et par le fil,\nqu’il en soit ainsi, qu’il en soit ainsi.",
 var:["Pour une liaison de protection de soi-même (s’empêcher d’envoyer des messages à un ex, par exemple), mets ton propre nom et la situation.","Dans la liaison des mains, ou handfasting, le cordon noué sert au contraire à unir un couple le jour de son mariage païen."],
 note:"Les Grecs gravaient des « katadesmoi », des tablettes de liaison en plomb qu’ils perçaient d’un clou et jetaient dans les puits. Selon Gerald Gardner, des sorcières de la New Forest auraient tenu en 1940 une grande cérémonie, le « cône de pouvoir », pour empêcher l’invasion nazie de l’Angleterre. Beaucoup de traditions wiccanes réservent la liaison aux cas graves, quand quelqu’un fait réellement du mal.",
 after:"Si un jour la liaison n’a plus lieu d’être, coupe les nœuds un à un, brûle la cordelette et remercie.",
 warn:"Une liaison ne remplace pas une plainte, une main courante ou la protection de professionnels en cas de danger. Elle vient en plus, jamais à la place.",
 m:"Je retiens la main, je ne blesse pas."},

{id:"congel",ch:"liaison",n:"Le sort du congélateur",sub:"Geler une rumeur ou une situation qui s’emballe",lvl:1,moon:"Décroissante",day:"Samedi",dur:"10 min",
 ing:["un papier","un petit récipient ou un sachet de congélation","de l’eau","une pincée de sel","un congélateur"],
 steps:["Écris sur le papier ce que tu veux arrêter : « Les rumeurs sur moi au bureau », « Ce conflit qui grossit ».","Plie le papier vers l’extérieur, loin de toi.","Mets-le dans le récipient, ajoute le sel et couvre d’eau.","Récite l’incantation, ferme le récipient et range-le tout au fond du congélateur.","N’y touche plus."],
 inc:"Langue qui court, langue qui mord,\nte voilà prise, gelée, qui dort.\nDans le froid tu ne bouges plus,\nce qui fut dit n’est plus rien du tout.",
 var:["Ajoute un peu de vinaigre à l’eau pour « aigrir » le ragot.","Certains ajoutent une gousse de piment pour que la rumeur brûle celui qui la répète."],
 note:"C’est l’un des sorts les plus populaires de la sorcellerie contemporaine américaine, justement parce qu’il est simple et qu’il n’abîme personne. Il suspend une situation sans rien détruire.",
 after:"Quand le problème est réglé, décongèle le récipient et vide l’eau dans l’évier en laissant couler l’eau du robinet.",
 m:"On suspend, on ne détruit pas."},

{id:"miel",ch:"liaison",n:"Le pot de miel adoucissant",sub:"Rendre une relation plus douce",lvl:2,moon:"Croissante",day:"Vendredi",dur:"30 min + entretien",
 ing:["un petit pot de miel (ou de sucre ou de sirop)","un papier et un crayon","des pétales de rose, de la cannelle, de la lavande","une bougie chauffe-plat rose ou blanche"],
 steps:["Écris ton nom sur le papier, puis, par-dessus en croix, le nom de la relation : ton patron, ta belle-mère, ton frère… ou le nom d’un groupe (« mon équipe »).","Écris autour, en cercle et sans lever le crayon, ce que tu souhaites : « Paix, douceur, bonne entente ».","Plie le papier vers toi et enfonce-le dans le miel en disant : « Comme ce miel est doux pour moi, que tu sois doux envers moi. »","Goûte un peu de miel sur ton doigt, puis ajoute les herbes et referme le pot.","Pose la bougie sur le couvercle et laisse-la brûler.","Rallume une bougie sur le pot chaque vendredi tant que la relation en a besoin."],
 inc:"Miel doré, miel d’abeille,\nque sa parole soit pareille.\nQue la colère devienne douceur,\nque nos deux cœurs soient sans rancœur.",
 var:["Un pot de miel pour soi-même : pour être plus doux avec soi, mets seulement ton nom.","Version sucre pour une relation professionnelle, sirop d’érable pour une amitié."],
 note:"Le « honey jar » vient du hoodoo afro-américain. On y « sucre » quelqu’un, on ne le force pas : le but est d’apaiser, pas de soumettre. On le pratique avec respect pour cette tradition.",
 after:"Quand la relation s’est apaisée, enterre le pot au pied d’un arbre fruitier ou jette-le avec gratitude.",
 m:"On adoucit, on ne force pas."},

{id:"coupure",ch:"liaison",n:"La coupure du cordon",sub:"Se détacher d’un lien qui fait mal",lvl:2,moon:"Décroissante",day:"Samedi",dur:"30 min",
 ing:["deux bougies (une pour toi, une pour l’autre personne ou la situation)","un fil de coton d’environ 30 cm","une paire de ciseaux ou un couteau","une coupelle résistante à la chaleur"],
 steps:["Place les deux bougies à une vingtaine de centimètres l’une de l’autre. Attache le fil à la base de chacune pour les relier.","Allume les deux bougies. Prends le temps de dire à voix haute ce que ce lien t’a apporté, en bien et en mal.","Récite l’incantation, puis coupe le fil au milieu.","Rapproche ta bougie de toi. Éloigne l’autre.","Laisse le fil brûler à la flamme des bougies, au-dessus de la coupelle. Laisse-les se consumer."],
 inc:"Ce qui nous liait, je le délie,\nje te rends ta part, je garde ma vie.\nVa ton chemin, je vais le mien,\nsans colère et sans lien.",
 var:["Pour une rupture amoureuse, un deuil, un ancien emploi ou une ville quittée.","Dans une version plus douce, dénoue le fil au lieu de le couper."],
 note:"Le « cord-cutting » est l’un des rituels les plus pratiqués par les sorcières modernes, souvent en complément d’un travail en thérapie.",
 after:"Jette les restes de la bougie de l’autre loin de chez toi. Garde les restes de la tienne ou enterre-les dans un pot.",
 m:"Je te rends ta part, je garde ma vie."},

/* ===================== IV. AMOUR ===================== */
{id:"amoursoi",ch:"amour",n:"Le miroir d’amour de soi",sub:"Le premier des sorts d’amour",lvl:1,moon:"Croissante ou pleine",day:"Vendredi",dur:"20 min",
 ing:["un miroir","une bougie rose","un quartz rose","des pétales de rose","un rouge à lèvres ou un crayon effaçable"],
 steps:["Allume la bougie rose devant le miroir, dans une pièce éclairée seulement par elle.","Tiens le quartz rose contre ton cœur et regarde-toi dans les yeux pendant une minute, sans te juger.","Écris sur le miroir, au rouge à lèvres, un mot qui te décrit tel que tu voudrais te voir : « lumineuse », « courageux », « digne ».","Dis trois choses que tu aimes chez toi, à voix haute. Elles doivent être vraies.","Récite l’incantation, puis souffle doucement sur le miroir.","Laisse le mot sur le miroir une semaine."],
 inc:"Visage aimé dans le miroir,\nje te regarde avec espoir.\nCe que je cherche chez les autres,\nje me le donne, c’est le nôtre.",
 var:["Répète le rituel chaque vendredi pendant un cycle lunaire complet.","Garde le quartz rose sous ton oreiller."],
 note:"Presque tous les grimoires modernes placent l’amour de soi en tête du chapitre amoureux. Sans lui, disent-ils, les autres sorts d’amour attirent ce qui nous ressemble dans nos blessures.",
 after:"Efface le miroir avec de l’eau de rose. Les pétales se sèchent pour un futur sachet.",
 m:"On attire ce qu’on croit mériter."},

{id:"attirer",ch:"amour",n:"Le sachet d’attraction",sub:"Attirer un amour qui nous correspond, sans viser personne",lvl:2,moon:"Croissante",day:"Vendredi",dur:"40 min",
 ing:["un carré de tissu rouge ou rose","des boutons de rose séchés","de la lavande","un bâton de cannelle","une pincée de pétales de jasmin ou de fleur d’oranger","un quartz rose ou une pierre de lune","un ruban rouge","un papier avec la liste des qualités recherchées"],
 steps:["Écris sur le papier les qualités de la relation que tu souhaites : respect, humour, tendresse… Aucun nom, aucun visage connu.","Pose le papier au centre du tissu et dépose chaque plante en disant ce qu’elle apporte : la rose, l’amour ; la lavande, la paix ; la cannelle, la passion ; le jasmin, la douceur.","Pose la pierre en dernier.","Ferme avec le ruban en faisant un nœud et une boucle. Récite l’incantation.","Porte le sachet sur toi le vendredi, ou garde-le près de ton lit."],
 inc:"Rose et cannelle, lavande et jasmin,\nqu’un cœur sincère croise mon chemin.\nQu’il vienne libre, qu’il vienne vrai,\nqu’on se choisisse, et à jamais.",
 var:["Ajoute une goutte de ton parfum pour le « signer ».","Dans la tradition anglaise, on offrait un « love-knot », un ruban noué de façon compliquée."],
 note:"La règle d’éthique de la Wicca est stricte : ne pas plier la volonté d’autrui. On définit donc la relation, pas la personne. C’est aussi ce qui, d’après les pratiquantes, rend le sort efficace.",
 after:"Quand tu as trouvé, enterre les herbes au pied d’un rosier et garde la pierre.",
 m:"Aucun nom, aucun visage."},

{id:"pomme",ch:"amour",n:"La pomme partagée",sub:"Raviver un couple",lvl:1,moon:"Pleine",day:"Vendredi",dur:"15 min",
 ing:["une belle pomme rouge","un couteau","du miel","de la cannelle","une bougie rouge"],
 steps:["Allume la bougie. Coupe la pomme en deux horizontalement pour faire apparaître l’étoile à cinq branches de ses pépins.","Sur une moitié, verse un filet de miel. Sur l’autre, une pincée de cannelle.","Chacun écrit du bout du doigt sur sa moitié un souhait pour le couple.","Échangez vos moitiés et mangez-les en vous regardant.","Récitez l’incantation ensemble, ou dites-vous simplement une chose que vous aimez chez l’autre."],
 inc:"Pomme d’Avalon, étoile cachée,\nque notre amour soit rallumé.\nCe que tu as, je te le donne,\nce que je suis, je te le donne.",
 var:["Seul, pour attirer : mange la moitié au miel et offre l’autre à la terre.","Garde les pépins et plante-les au printemps."],
 note:"La pomme est le fruit de l’amour et de l’immortalité dans les mythes celtes et grecs : l’île d’Avalon est « l’île des pommes », et la pomme d’or de la discorde déclenche la guerre de Troie. L’étoile de pépins en fait un pentacle naturel.",
 after:"Les trognons se compostent ou s’offrent aux oiseaux.",
 m:"Coupe-la à l’horizontale."},

{id:"reconciliation",ch:"amour",n:"La réconciliation",sub:"Réparer une amitié ou un lien abîmé",lvl:2,moon:"Croissante",day:"Lundi ou vendredi",dur:"30 min",
 ing:["deux bougies roses","un ruban rose","un quartz rose","une photo de vous deux, ou deux papiers portant vos noms","du sucre"],
 steps:["Place les bougies aux deux extrémités d’une table, à environ 50 cm l’une de l’autre, et la photo au centre.","Allume-les. Saupoudre un chemin de sucre entre les deux.","Chaque jour pendant sept jours, allume les bougies dix minutes et rapproche-les de quelques centimètres.","Le septième jour, les bougies se touchent. Noue le ruban autour de la photo avec le quartz rose.","Récite l’incantation, puis fais un vrai geste : un message, un appel, une excuse."],
 inc:"Ce qui fut brisé se recoud,\nce qui fut dit, on le dénoue.\nQue nos chemins se rejoignent encore,\ncomme la lune revient d’or.",
 var:["Pour une famille, une bougie par personne, toutes rapprochées vers le centre.","Mets une pincée de sucre dans ton message écrit (littéralement dans l’enveloppe) si tu envoies une lettre."],
 note:"Rapprocher des bougies jour après jour est une technique classique de la magie des bougies. Elle rend visible, dans le monde physique, le mouvement qu’on souhaite.",
 after:"Offre le ruban à la personne si la réconciliation se fait. Sinon, dénoue-le et garde le quartz.",
 m:"Le sort ouvre la porte, à toi de la franchir."},

/* ===================== V. PROSPÉRITÉ ===================== */
{id:"cannelle",ch:"prosperite",n:"Le souffle de cannelle",sub:"Le premier jour du mois",lvl:1,moon:"Toutes phases",day:"Le 1ᵉʳ du mois",dur:"2 min",
 ing:["une pincée de cannelle en poudre","ta porte d’entrée"],
 steps:["Le premier jour du mois, au matin, pose-toi à ta porte d’entrée ouverte, côté extérieur.","Mets la cannelle au creux de ta main droite.","Récite l’incantation, puis souffle la cannelle vers l’intérieur de la maison.","Ne balaie pas le seuil avant le soir."],
 inc:"Quand cette cannelle soufflera,\nla prospérité viendra.\nQuand cette cannelle s’envolera,\nl’abondance ici restera.",
 var:["Au bureau, souffle-la sur ton seuil ou dans ton portefeuille ouvert.","Ajoute du sucre pour la douceur et un peu de sel pour la protection."],
 note:"Ce petit rituel est devenu viral sur les réseaux sociaux américains dans les années 2020. La cannelle est l’épice de la chaleur et du succès dans les correspondances traditionnelles, liée au Soleil.",
 after:"Balaie la cannelle vers l’intérieur le soir.",
 m:"Vers l’intérieur, jamais vers l’extérieur."},

{id:"abondance",ch:"prosperite",n:"Le bocal d’abondance",sub:"Une réserve de chance qui se remplit",lvl:2,moon:"Croissante, de la nouvelle à la pleine",day:"Jeudi",dur:"45 min + entretien",
 ing:["un bocal en verre","du riz (pour la multiplication)","du basilic","de la menthe séchée","trois feuilles de laurier","un bâton de cannelle","une citrine ou une aventurine","des pièces de monnaie (dorées et argentées)","un billet ou un papier vert","une bougie verte"],
 steps:["Allume la bougie verte. Sur le papier, écris ton objectif précis, avec un chiffre si possible : « Gagner 300 € de plus par mois », « Trouver un CDI ».","Plie le papier vers toi et place-le au fond du bocal.","Ajoute le riz : « Que cela se multiplie. »","Ajoute le basilic et la menthe : « Que cela pousse. »","Pose les trois feuilles de laurier : « Que cela réussisse. »","Plante le bâton de cannelle au centre, ajoute la pierre et les pièces.","Ferme, scelle avec la cire de la bougie verte et récite l’incantation.","Chaque jeudi, ajoute une pièce dans le bocal."],
 inc:"Grain de riz, feuille qui croît,\npièce qui tinte, viens vers moi.\nQue ce bocal se remplisse,\net ma bourse s’épanouisse.",
 var:["Pour une entreprise, place le bocal près de la caisse ou du bureau.","Le bocal peut se secouer doucement quand tu as besoin d’un coup de pouce."],
 note:"Les « money jars » sont un classique de la sorcellerie populaire américaine. Le riz symbolise la multiplication dans de nombreuses cultures, d’où la coutume d’en lancer sur les jeunes mariés.",
 after:"Quand l’objectif est atteint, dépense les pièces pour quelque chose d’utile et de joyeux, et recommence un bocal pour le suivant.",
 m:"Une pièce chaque jeudi."},

{id:"emploi",ch:"prosperite",n:"Le sort de l’entretien",sub:"Pour obtenir un poste",lvl:2,moon:"Croissante",day:"Jeudi ou dimanche",dur:"30 min, la veille",
 ing:["une bougie orange ou dorée","ton CV ou l’annonce imprimée","de l’huile d’olive","du romarin (mémoire) et du laurier (victoire)","une cornaline ou une citrine"],
 steps:["La veille de l’entretien, grave ton nom et le nom de l’entreprise sur la bougie.","Enduis-la d’huile de bas en haut (pour attirer), puis roule-la dans le romarin écrasé.","Pose-la sur l’annonce. Allume-la.","Relis l’annonce et imagine l’appel qui t’annonce que tu es pris, en détail.","Récite l’incantation, puis prépare vraiment ton entretien pendant qu’elle brûle.","Le jour J, glisse une feuille de laurier dans ta chaussure droite et la cornaline dans ta poche."],
 inc:"Laurier de la victoire,\nromarin de la mémoire,\nque je parle clair et droit,\nque ce poste soit pour moi.",
 var:["Pour un examen, remplace l’annonce par ta convocation et le laurier par de la menthe.","Pour une augmentation, travaille un jeudi avec une bougie verte."],
 note:"Le laurier couronnait les vainqueurs des jeux pythiques en l’honneur d’Apollon. Le romarin était l’herbe du souvenir : les étudiants grecs en portaient des couronnes pendant les examens.",
 after:"Garde la feuille de laurier en souvenir si tu obtiens le poste.",
 m:"La magie aide ceux qui préparent."},

{id:"pieces",ch:"prosperite",n:"Les pièces de pleine lune",sub:"Montrer son argent à la lune",lvl:1,moon:"Pleine",day:"Toutes",dur:"5 min",
 ing:["des pièces de monnaie","un bol d’eau","la lumière de la pleine lune"],
 steps:["Un soir de pleine lune, remplis un bol d’eau et place-le là où la lune s’y reflète.","Mets les pièces dans l’eau.","Passe tes mains au-dessus du bol comme pour ramasser la lumière.","Récite l’incantation.","Le lendemain matin, sèche les pièces et garde-les dans ton portefeuille pendant un mois."],
 inc:"Belle lune, je te montre ma bourse,\nqu’elle soit pleine à la fin de ta course.\nComme tu grandis et reviens toujours,\nque l’argent revienne, jour après jour.",
 var:["Retourne les pièces dans ta poche à la vue de la nouvelle lune.","Arrose tes plantes avec l’eau du bol."],
 note:"En Angleterre et en France, la coutume de retourner l’argent de sa poche en voyant la première lune du mois est attestée depuis des siècles dans le folklore.",
 after:"Dépense les pièces au bout d’un mois, l’argent doit circuler.",
 m:"L’argent doit circuler."},

{id:"chance",ch:"prosperite",n:"Le charme du trèfle",sub:"Un porte-bonheur fait maison",lvl:1,moon:"Croissante",day:"Dimanche",dur:"20 min",
 ing:["une petite fiole en verre ou un médaillon","une feuille de trèfle (à trois ou quatre feuilles)","une pincée de camomille","un grain de poivre de la Jamaïque ou un clou de girofle","une aventurine verte en éclat"],
 steps:["Place chaque ingrédient dans la fiole en le nommant.","Ferme et tiens la fiole au soleil de midi en récitant l’incantation.","Porte-la en collier ou garde-la dans ta poche.","Quand quelque chose de bon arrive, touche-la et dis merci."],
 inc:"Trèfle des prés, soleil de midi,\nque la chance soit ma compagnie.\nAu hasard des routes et des jeux,\nque le sort me soit heureux.",
 var:["Remplace le trèfle par une feuille de laurier si tu n’en trouves pas.","Les joueurs de cartes frottaient autrefois leurs mains de camomille avant de jouer."],
 note:"Le trèfle à quatre feuilles est l’un des porte-bonheur les plus connus d’Europe. En Irlande, on dit que ses quatre feuilles sont la foi, l’espoir, l’amour et la chance.",
 after:"Si la fiole se casse, c’est qu’elle a épuisé sa chance : fais-en une nouvelle.",
 m:"Touche-la et dis merci."},

/* ===================== VI. BIEN-ÊTRE ===================== */
{id:"poupee",ch:"bienetre",n:"La poupée de soin",sub:"Accompagner la convalescence d’un proche",lvl:2,moon:"Croissante",day:"Dimanche (Soleil, la santé)",dur:"1 h",
 ing:["deux morceaux de tissu en coton (bleu ou vert) découpés en forme de silhouette","du fil et une aiguille","de la lavande, de la camomille, du thym, de la mélisse","un petit papier avec le nom de la personne (avec son accord)","du coton de rembourrage","une bougie bleue"],
 steps:["Demande d’abord l’accord de la personne. C’est une règle absolue.","Couds les deux silhouettes ensemble en laissant une ouverture sur le côté.","Allume la bougie bleue. Remplis la poupée de coton et d’herbes en nommant chacune : lavande pour le repos, camomille pour le calme, thym pour la force, mélisse pour le moral.","Glisse le papier portant le nom au niveau du cœur et referme.","Tiens la poupée entre tes mains et imagine la personne en bonne santé, en train de rire.","Récite l’incantation et garde la poupée dans un tissu propre, ou offre-la à la personne."],
 inc:"Petite image de toi cousue,\nque la force te soit rendue.\nQue le repos te soit doux,\net la santé revienne à nous.",
 var:["Pour toi-même : mets ton nom et place la poupée sur ta table de nuit.","Chaque dimanche, rallume une bougie bleue à côté de la poupée."],
 note:"On croit souvent que les poupées magiques servent à nuire, mais elles ont aussi été utilisées pour guérir, dans les mondes grec, égyptien et européen. On les appelle « poppets » en anglais.",
 after:"Une fois la personne guérie, ouvre la poupée, enterre les herbes et brûle ou garde le tissu.",
 warn:"Ce sort ne soigne rien. Il accompagne une personne qui suit ses traitements.",
 m:"Toujours avec l’accord de la personne."},

{id:"eaucalme",ch:"bienetre",n:"L’eau d’apaisement",sub:"Contre l’angoisse du quotidien",lvl:1,moon:"Pleine",day:"Lundi",dur:"5 min + une nuit",
 ing:["une bouteille en verre d’eau de source","une améthyste (bien lavée)","trois brins de lavande","une étiquette"],
 steps:["Un soir de pleine lune, place l’améthyste dans la bouteille et ajoute la lavande.","Pose la bouteille sur le rebord d’une fenêtre, à la lumière de la lune.","Récite l’incantation, les deux mains posées sur la bouteille.","Le lendemain, retire la lavande et étiquette la bouteille avec la date.","Mets l’eau dans un vaporisateur et vaporise-la autour de toi (jamais dans les yeux) quand tu te sens tendu."],
 inc:"Eau de lune, eau d’argent,\ncalme mon cœur et mon sang.\nQue le souci glisse sur moi\ncomme la pluie sur le bois.",
 var:["Ajoute-la à ton bain du soir.","Arrose tes plantes d’intérieur avec le reste."],
 note:"L’améthyste doit son nom au grec « amethystos », « qui n’est pas ivre ». Les Grecs pensaient qu’elle protégeait de l’ivresse et des excès.",
 after:"L’eau se conserve un mois, à l’abri de la lumière.",
 warn:"Ne bois pas l’eau où a trempé une pierre, certaines pierres sont toxiques. Cette eau se vaporise, elle ne se boit pas.",
 m:"Se vaporise, ne se boit pas."},

{id:"ancrage",ch:"bienetre",n:"L’arbre intérieur",sub:"Un exercice d’ancrage en cinq minutes",lvl:1,moon:"Toutes phases",day:"Tous",dur:"5 min",
 ing:["une pierre sombre (hématite, tourmaline noire ou un simple caillou)","les pieds nus, si possible sur la terre"],
 steps:["Debout ou assis, pose les pieds bien à plat. Tiens la pierre dans la main gauche.","Ferme les yeux. Respire en comptant jusqu’à quatre, retiens jusqu’à quatre, expire jusqu’à six.","Imagine des racines qui sortent de tes pieds et descendent dans la terre, profondément, jusqu’au cœur chaud de la planète.","À chaque expiration, envoie dans les racines ce qui t’agite. À chaque inspiration, fais remonter une énergie calme et chaude.","Imagine enfin des branches qui sortent du haut de ta tête et touchent le ciel.","Récite l’incantation et ouvre les yeux."],
 inc:"Racines en bas, branches en haut,\nje suis l’arbre, je suis l’eau.\nLe vent peut souffler, je ne tombe pas,\nla terre me tient, la terre est là.",
 var:["Fais-le avant et après chaque rituel : c’est la base de toute la pratique.","Au bureau, fais-le discrètement, les mains posées sur les cuisses."],
 note:"L’ancrage et le centrage, « grounding and centering », sont enseignés dès le premier jour dans la sorcellerie moderne. L’exercice de l’arbre a été popularisé par la sorcière américaine Starhawk dans « The Spiral Dance » (1979).",
 after:"Pose la pierre sur ton autel ou garde-la dans ta poche.",
 m:"La base de toute pratique."},

{id:"infusion",ch:"bienetre",n:"L’infusion des trois sœurs",sub:"Une potion de réconfort à boire",lvl:1,moon:"Toutes phases",day:"Tous",dur:"10 min",
 ing:["1 cuillère à café de camomille","1 cuillère à café de tilleul","1 cuillère à café de mélisse","une cuillère de miel","une tasse d’eau frémissante"],
 steps:["Fais chauffer l’eau sans la faire bouillir.","Mets les trois plantes dans la théière en disant leurs noms.","Verse l’eau et remue trois fois dans le sens des aiguilles d’une montre.","Laisse infuser sept minutes en tenant la théière entre tes mains.","Ajoute le miel, récite l’incantation au-dessus de la tasse et bois lentement."],
 inc:"Camomille, tilleul et mélisse,\nque la tension se dissipe et glisse.\nTrois sœurs de l’été dans ma tasse,\nque la douceur prenne la place.",
 var:["Ajoute une rondelle d’orange et une étoile de badiane en hiver.","À boire en préparation d’un rituel de sommeil."],
 note:"Ces trois plantes entrent depuis des siècles dans les tisanes du soir. Les « potions » de sorcière étaient souvent tout simplement des remèdes de cuisine.",
 after:"Offre les plantes infusées au compost.",
 warn:"Demande conseil en cas de grossesse, d’allergie ou de traitement médical.",
 m:"La plus douce des potions."}
];
