window.SPELLS=window.SPELLS.concat([
/* ===================== VII. RÊVES ===================== */
{id:"armoise",ch:"reves",n:"L’oreiller d’armoise",sub:"Pour des rêves vifs et dont on se souvient",lvl:1,moon:"Pleine ou croissante",day:"Lundi",dur:"30 min",
 ing:["deux carrés de tissu de 15 cm (bleu nuit ou violet)","de l’armoise séchée","de la lavande","des pétales de rose","une pincée de houblon (facultatif, pour le sommeil)","du fil et une aiguille"],
 steps:["Couds trois côtés des carrés pour former une petite pochette.","Remplis-la d’armoise, de lavande et de rose, en proportions égales.","Avant de coudre le dernier côté, murmure l’incantation dans l’ouverture comme pour y enfermer tes mots.","Referme et glisse le petit coussin dans ta taie d’oreiller.","Pose un carnet et un crayon à côté du lit. Au réveil, note tes rêves avant de bouger ou de parler."],
 inc:"Armoise d’argent, porte de la nuit,\nouvre les rêves, chasse l’ennui.\nCe que je vois quand je suis loin,\nque je m’en souvienne au matin.",
 var:["Retire l’armoise si tes rêves deviennent trop intenses : garde lavande et houblon pour le sommeil seul.","Remplace-le tous les trois mois."],
 note:"L’armoise est la grande plante des rêves en Europe. On la plaçait sous l’oreiller la nuit de la Saint-Jean pour rêver de son avenir.",
 after:"Les herbes usées se brûlent lors d’une fumigation ou retournent à la terre.",
 warn:"L’armoise est déconseillée pendant la grossesse. On la respire, on ne la consomme pas.",
 m:"Note tes rêves avant de parler."},

{id:"laurierreve",ch:"reves",n:"La feuille de laurier sous l’oreiller",sub:"Poser une question à ses rêves",lvl:1,moon:"Pleine",day:"Lundi",dur:"5 min",
 ing:["une feuille de laurier séchée","un feutre","un verre d’eau"],
 steps:["Juste avant de dormir, écris ta question sur la feuille de laurier en un ou deux mots.","Pose le verre d’eau sur ta table de nuit.","Glisse la feuille sous ton oreiller et récite l’incantation trois fois, les yeux fermés.","Au réveil, bois l’eau d’un trait et note ce dont tu te souviens.","Recommence trois nuits de suite si rien ne vient."],
 inc:"Laurier d’Apollon qui voit loin,\nporte ma question jusqu’au matin.\nQue le rêve me réponde clair,\nsans détour et sans mystère.",
 var:["Pour la nuit de la Saint-Valentin, la tradition anglaise épinglait cinq feuilles de laurier sur l’oreiller pour rêver de son futur amour."],
 note:"La Pythie de Delphes, qui rendait les oracles d’Apollon, était associée au laurier : elle en tenait une branche, et certains auteurs rapportent qu’elle en mâchait les feuilles.",
 after:"Brûle la feuille dans une coupelle quand tu as ta réponse.",
 m:"Une question, un ou deux mots."},

{id:"cauchemars",ch:"reves",n:"Le bocal anti-cauchemars",sub:"Pour les enfants et les grands",lvl:1,moon:"Décroissante",day:"Samedi",dur:"20 min",
 ing:["un petit bocal","de la lavande","de la camomille","une pincée de sel","une améthyste ou un quartz clair","une paillette ou une étoile en papier doré","un ruban bleu"],
 steps:["Si c’est pour un enfant, fais-le avec lui : c’est lui qui dépose chaque ingrédient.","Lavande pour le calme, camomille pour la douceur, sel pour la protection, pierre pour la garde.","Ajoute l’étoile dorée : c’est la veilleuse qui brille dans le noir.","Ferme, noue le ruban et récite l’incantation ensemble.","Pose le bocal près du lit. Il « avale » les mauvais rêves."],
 inc:"Petit bocal au bord du lit,\nmange les monstres de la nuit.\nNe laisse passer que les jolis rêves,\njusqu’à ce que le soleil se lève.",
 var:["Tu peux le secouer comme une boule à neige si un cauchemar revient."],
 note:"Les objets gardiens du sommeil existent partout, des amulettes égyptiennes du dieu Bès aux anges gardiens peints au-dessus des berceaux européens.",
 after:"Renouvelle les herbes à chaque changement de saison.",
 m:"À faire avec l’enfant."},

/* ===================== VIII. DIVINATION ===================== */
{id:"miroirnoir",ch:"divination",n:"Le miroir noir",sub:"Fabriquer et utiliser un miroir de voyance",lvl:3,moon:"Pleine ou noire",day:"Lundi",dur:"1 h pour le fabriquer, 20 min par séance",
 ing:["un cadre photo avec sa vitre","de la peinture noire mate (acrylique ou en bombe)","de l’armoise en infusion","deux bougies","un endroit sombre"],
 steps:["Fabrication : sors la vitre du cadre, lave-la avec l’infusion d’armoise et laisse-la sécher.","Peins l’un des côtés en noir, en plusieurs couches fines. Remets la vitre dans le cadre, côté peint à l’intérieur.","Consacre le miroir sous la pleine lune en passant sur lui la fumée d’une herbe, puis garde-le enveloppé dans un tissu noir.","Séance : place deux bougies derrière toi ou sur les côtés, pour qu’aucune flamme ne se reflète.","Pose une question, puis regarde dans le miroir sans fixer, les yeux détendus, comme pour voir à travers.","Au bout de quelques minutes, des brumes, des couleurs ou des images peuvent apparaître. Laisse-les venir sans les chercher.","Récite l’incantation au début et note tout après la séance."],
 inc:"Miroir de nuit, eau sans fond,\nmontre-moi ce que je ne vois pas.\nQue les brumes s’écartent et s’ouvrent,\net que la vérité se découvre.",
 var:["Un bol d’eau teintée d’encre noire sert de miroir liquide.","Nostradamus aurait pratiqué la voyance dans un bol d’eau posé sur un trépied de bronze."],
 note:"John Dee, astrologue d’Élisabeth Iʳᵉ d’Angleterre, possédait un miroir d’obsidienne venu du Mexique aztèque. On peut toujours le voir au British Museum.",
 after:"Enveloppe toujours le miroir dans son tissu après usage.",
 m:"Regarder à travers, pas dessus."},

{id:"cire",ch:"divination",n:"La céromancie",sub:"Lire la cire dans l’eau froide",lvl:1,moon:"Pleine",day:"Lundi, ou le soir de Samhain",dur:"15 min",
 ing:["une bougie blanche","un grand bol d’eau très froide","une cuillère (facultatif)"],
 steps:["Formule une question précise.","Allume la bougie et laisse la cire fondre pendant quelques minutes.","Incline la bougie au-dessus du bol et laisse couler un filet de cire dans l’eau, d’un geste continu.","Récite l’incantation pendant que la cire tombe.","Sors la forme figée et regarde-la à la lumière, puis son ombre sur le mur.","Note ta première impression. Voir la liste des symboles dans le chapitre Divination."],
 inc:"Cire qui coule, cire qui fige,\ndis-moi ce qui se dirige.\nDans l’eau froide, montre la forme\nde ce qui vient et se transforme.",
 var:["En Ukraine et en Russie, on fondait de la cire ou du plomb dans l’eau la veille de Noël ou de la Saint-André.","En Finlande, on fait encore fondre de l’étain au Nouvel An (« uudenvuodentina »)."],
 note:"La céromancie, du grec « kêros », la cire, et « manteia », la divination, était pratiquée dans toute l’Europe du Nord et de l’Est, surtout pendant les fêtes d’hiver.",
 after:"Garde la forme de cire dans ton Livre des Ombres si elle te parle.",
 m:"La première impression compte."},

{id:"the",ch:"divination",n:"La tasse de thé",sub:"La tasséographie, pas à pas",lvl:2,moon:"Toutes phases",day:"Tous",dur:"20 min",
 ing:["du thé en vrac à grandes feuilles (pas de sachet)","une tasse claire, large, avec une soucoupe","de l’eau chaude"],
 steps:["Mets une pincée de feuilles directement dans la tasse et verse l’eau.","Bois lentement en pensant à ta question, jusqu’à ce qu’il ne reste qu’une cuillère de liquide au fond.","Prends la tasse de la main gauche et fais-la tourner trois fois dans le sens des aiguilles d’une montre.","Retourne-la d’un coup sur la soucoupe et attends une minute que le liquide s’écoule.","Relève-la. L’anse représente toi-même. Les feuilles près du bord parlent du présent, celles du fond d’un avenir plus lointain.","Cherche des formes : animaux, lettres, objets. Voir le dictionnaire du chapitre Divination."],
 inc:"Feuille de thé, feuille d’or,\nmontre-moi ce qui dort.\nAu bord, aujourd’hui, au fond, demain,\ntrace pour moi le chemin.",
 var:["Le marc de café se lit de la même façon au Moyen-Orient et en Grèce (« kafemanteia »)."],
 note:"La lecture des feuilles de thé s’est répandue en Europe au XVIIᵉ siècle avec le commerce du thé. Les diseuses de bonne aventure de l’Angleterre victorienne en ont fait un art populaire.",
 after:"Les feuilles vont au compost.",
 m:"L’anse, c’est toi."},

{id:"pendule",ch:"divination",n:"Le pendule",sub:"Oui, non, peut-être",lvl:1,moon:"Toutes phases",day:"Tous",dur:"10 min",
 ing:["un pendule (un cristal, une bague ou une clé au bout d’une chaîne de 20 cm suffit)","une feuille avec OUI, NON et PEUT-ÊTRE écrits en cercle (facultatif)"],
 steps:["Tiens la chaîne entre le pouce et l’index, le coude posé sur la table, le pendule immobile.","Demande-lui : « Montre-moi oui. » Observe son mouvement (souvent un cercle ou un va-et-vient). Puis : « Montre-moi non. »","Pose une question qui se répond par oui ou par non. Garde l’esprit neutre, sans espérer une réponse.","Récite l’incantation avant la première question.","Remercie le pendule à la fin et range-le dans un sachet."],
 inc:"Pendule de fil, pendule d’argent,\ndis-moi le vrai, simplement.\nNi mon désir ni ma crainte,\nseulement la réponse sans feinte.",
 var:["Au-dessus d’une carte, il sert à chercher un objet perdu : c’est la radiesthésie."],
 note:"Les sourciers utilisent des baguettes et des pendules pour chercher l’eau depuis au moins le XVIᵉ siècle. Les scientifiques expliquent le mouvement par l’effet idéomoteur : de minuscules gestes inconscients de la main.",
 after:"Aucun reste.",
 m:"Garde l’esprit neutre."},

{id:"pelure",ch:"divination",n:"La pelure de pomme",sub:"Une divination d’amour de Samhain",lvl:1,moon:"Toutes phases",day:"Nuit de Samhain (31 octobre)",dur:"5 min",
 ing:["une pomme","un couteau éplucheur"],
 steps:["À minuit, ou à la lueur d’une bougie, épluche la pomme d’un seul tenant sans casser la pelure.","Récite l’incantation en tenant la pelure.","Lance-la par-dessus ton épaule gauche.","Regarde la forme qu’elle prend en tombant : on y lit la première lettre du prénom de son futur amour."],
 inc:"Pelure de pomme d’un seul tenant,\nje te lance au vent.\nPar-dessus mon épaule, dis-moi\nla lettre de celui qui viendra.",
 var:["Si la pelure casse, la tradition dit qu’on ne se mariera pas cette année."],
 note:"C’est un jeu de divination d’Halloween des îles Britanniques, attesté notamment au XVIIIᵉ et au XIXᵉ siècle. Le poète écossais Robert Burns décrit ces coutumes d’Halloween dans son poème « Halloween » (1785).",
 after:"Mange la pomme !",
 m:"D’un seul tenant."},

/* ===================== IX. GLAMOUR ===================== */
{id:"glamour",ch:"glamour",n:"Le glamour du matin",sub:"Un charme qui se porte toute la journée",lvl:1,moon:"Croissante ou pleine",day:"Vendredi",dur:"5 min",
 ing:["ton miroir de salle de bain","de l’eau de rose ou ton parfum","un bijou que tu portes souvent"],
 steps:["Après ta toilette, regarde-toi dans le miroir.","Vaporise l’eau de rose ou le parfum sur tes poignets et à la base de ton cou.","Tiens ton bijou dans ta main et imagine une lumière dorée qui l’entoure puis t’enveloppe tout entier.","Récite l’incantation en mettant le bijou.","Chaque fois que tu le touches dans la journée, le charme se réactive."],
 inc:"Lumière d’or, voile de soie,\nque l’on voie en moi ce que je vois.\nQue ma présence soit claire et belle,\ndu matin jusqu’à la chandelle.",
 var:["Avant un rendez-vous important, ajoute un pétale de rose dans ta poche.","En hiver, utilise de l’huile d’orange douce diluée."],
 note:"En écossais ancien, « glamour » voulait dire un sort qui trompe les yeux. Walter Scott a fait passer le mot dans l’anglais courant au XIXᵉ siècle, avec le sens de charme séduisant.",
 after:"Le soir, en enlevant le bijou, remercie-le.",
 m:"Le charme se réactive au toucher."},

{id:"levres",ch:"glamour",n:"Le rouge enchanté",sub:"Pour une parole qui porte",lvl:1,moon:"Croissante",day:"Mercredi (la parole) ou vendredi (la séduction)",dur:"10 min",
 ing:["un rouge à lèvres ou un baume à lèvres","une bougie rouge ou orange","une cornaline"],
 steps:["Allume la bougie. Pose le rouge à lèvres fermé à côté de la cornaline.","Trace au-dessus un petit cercle avec ton doigt, trois fois.","Ouvre le tube et récite l’incantation en soufflant dessus.","Laisse-le près de la bougie pendant qu’elle brûle.","Désormais, applique-le avant une réunion, un oral ou une soirée : chaque application déclenche le charme."],
 inc:"Que ma bouche parle vrai,\nque ma voix porte, claire et gaie.\nCe que je dis soit entendu,\net ce que je veux, obtenu.",
 var:["Un baume incolore convient parfaitement, pour tous.","Tu peux enchanter de la même façon une cravate, un stylo ou une paire de chaussures."],
 note:"Enchanter un objet du quotidien est une technique typique de la sorcellerie moderne, dite « de cuisine » ou « du quotidien ».",
 after:"Aucun reste.",
 m:"Le charme est dans le geste."},

{id:"confiance",ch:"glamour",n:"La pierre du courage",sub:"Un talisman de confiance en soi",lvl:1,moon:"Croissante",day:"Mardi (Mars) ou dimanche (Soleil)",dur:"15 min",
 ing:["une cornaline, un œil-de-tigre ou une citrine","une bougie orange","du sel","un souvenir d’une réussite"],
 steps:["Nettoie la pierre en la posant une nuit sur du sel.","Allume la bougie. Tiens la pierre et rappelle-toi en détail un moment où tu as été fier de toi.","Pendant que tu revis ce souvenir, serre la pierre : tu y ranges cette sensation.","Récite l’incantation trois fois.","Porte-la sur toi. Quand tu as besoin de courage, serre-la et laisse remonter la sensation."],
 inc:"Pierre de feu, pierre de soleil,\ngarde ma force quand je sommeille.\nQuand je doute, rends-la-moi,\nque je me tienne droit.",
 var:["Recharge-la au soleil de midi une fois par mois.","Les psychologues appellent un peu la même chose un « ancrage » émotionnel."],
 note:"La cornaline était portée par les soldats de l’Antiquité, notamment en Égypte et à Rome, pour le courage. On la gravait souvent pour en faire des sceaux.",
 after:"Aucun reste.",
 m:"Tu y ranges ta propre force."},

/* ===================== X. ÉLÉMENTS ===================== */
{id:"quatre",ch:"elements",n:"Le sort des quatre éléments",sub:"Donner à une intention les quatre forces",lvl:2,moon:"Croissante",day:"Dimanche",dur:"30 min",
 ing:["un papier et un crayon","un bol de terre ou de sel (Terre)","un bâton d’encens ou une plume (Air)","une bougie (Feu)","un bol d’eau (Eau)"],
 steps:["Place les quatre éléments en croix autour de toi : Terre au nord, Air à l’est, Feu au sud, Eau à l’ouest.","Écris ton intention en une phrase.","Pose le papier sur la terre : « Terre, donne-lui un corps. »","Passe-le dans la fumée de l’encens : « Air, donne-lui des ailes. »","Passe-le au-dessus de la flamme, sans le brûler : « Feu, donne-lui la force. »","Asperge-le de trois gouttes d’eau : « Eau, donne-lui la vie. »","Récite l’incantation et range le papier sous ton oreiller ou sur ton autel."],
 inc:"Par la Terre qui porte,\npar l’Air qui transporte,\npar le Feu qui transforme,\npar l’Eau qui donne forme,\nque mon vœu prenne corps.",
 var:["Pour éloigner : même ordre, mais on brûle le papier à la fin et on disperse les cendres."],
 note:"La théorie des quatre éléments vient du philosophe grec Empédocle, au Vᵉ siècle av. J.-C. Elle a dominé la science européenne jusqu’au XVIIᵉ siècle et reste la base de la sorcellerie moderne et de l’astrologie.",
 after:"Rends la terre au jardin et l’eau à une plante.",
 m:"Nord, Est, Sud, Ouest."},

{id:"vents",ch:"elements",n:"La corde des vents",sub:"Le vieux sort des sorcières marines",lvl:2,moon:"Croissante",day:"Mercredi",dur:"20 min",
 ing:["une cordelette de chanvre ou de coton d’environ 60 cm","un jour de vent"],
 steps:["Un jour de vent, va dehors, face au vent, la cordelette en main.","Fais un premier nœud lâche en inspirant profondément : tu y enfermes une petite brise.","Fais un deuxième nœud plus serré : un vent fort.","Fais un troisième nœud très serré : la tempête.","Récite l’incantation. Garde la corde chez toi.","Quand tu manques d’élan dans un projet, défais le premier nœud ; le deuxième pour un vrai coup de fouet. Ne défais le troisième que dans l’urgence."],
 inc:"Vent du nord, vent du large,\nentre dans ma corde et prends ta charge.\nUn nœud la brise, deux le grand vent,\ntrois la tempête qui dort dedans.",
 var:["Fais une corde pour chaque projet important de l’année."],
 note:"Au Moyen Âge et jusqu’au XIXᵉ siècle, les marins achetaient aux sorcières des Shetland, de l’île de Man ou de Laponie des cordes à trois nœuds qui contenaient du vent. L’histoire est racontée notamment par Ranulf Higden au XIVᵉ siècle et reprise par James Frazer dans « Le Rameau d’or ».",
 after:"Quand les trois nœuds sont défaits, brûle la corde en remerciant le vent.",
 m:"Le troisième nœud, c’est la tempête."},

{id:"tempete",ch:"elements",n:"L’eau d’orage",sub:"Récolter la force de la tempête",lvl:1,moon:"Toutes phases",day:"Pendant un orage",dur:"5 min",
 ing:["un bocal propre","un orage (en restant à l’abri !)"],
 steps:["Quand un orage éclate, pose le bocal sur un rebord de fenêtre, un balcon ou dans le jardin, sans t’exposer toi-même.","Récite l’incantation depuis l’intérieur.","Rentre le bocal quand l’orage est passé. Ferme-le et note la date et l’heure.","Utilise-la pour les sorts qui ont besoin d’énergie : courage, bannissement, relancer un projet bloqué."],
 inc:"Pluie d’éclair, eau de tonnerre,\nremplis mon bocal de ta colère.\nQue ta force serve mon bon droit,\net qu’elle obéisse à ma voix.",
 var:["L’eau d’une pluie douce de printemps sert au contraire aux sorts de fertilité et de croissance."],
 note:"L’eau d’orage est un ingrédient apprécié de la sorcellerie moderne. Dans le folklore, l’eau de la première pluie de mai était réputée embellir le teint.",
 after:"Verse l’eau inutilisée au pied d’un arbre.",
 warn:"Ne sors jamais pendant un orage. Cette eau ne se boit pas.",
 m:"Reste toujours à l’abri."},

{id:"graine",ch:"elements",n:"La graine de printemps",sub:"Faire pousser un projet",lvl:1,moon:"Nouvelle lune",day:"Autour d’Ostara",dur:"15 min + un cycle",
 ing:["un pot de terre","des graines faciles (basilic, tournesol, cresson)","un petit papier biodégradable","de l’eau de lune"],
 steps:["Écris ton projet sur le papier en un mot.","Enfonce le papier dans la terre du pot, puis les graines par-dessus.","Arrose avec l’eau de lune en récitant l’incantation.","Pose le pot à la lumière. Chaque fois que tu arroses, fais aussi un geste concret pour ton projet.","Observe : la plante et le projet grandissent ensemble."],
 inc:"Graine dans la terre noire,\nporte mon rêve et mon espoir.\nComme tu montes vers le jour,\nque mon projet grandisse à son tour.",
 var:["Le cresson pousse en quelques jours : parfait pour un souhait urgent."],
 note:"Planter une intention est une métaphore commune à toutes les cultures agricoles. Dans la roue de l’année, Ostara, l’équinoxe de printemps, est la fête des graines.",
 after:"Garde la plante vivante le plus longtemps possible.",
 m:"Arroser, c’est agir."},

/* ===================== XI. LUNE ===================== */
{id:"eaudelune",ch:"lune",n:"L’eau de lune",sub:"L’ingrédient de base du grimoire",lvl:1,moon:"Pleine",day:"Toutes",dur:"5 min + une nuit",
 ing:["un bocal en verre avec couvercle","de l’eau de source ou filtrée","une pierre de lune ou un quartz clair (facultatif)"],
 steps:["Le soir de la pleine lune, remplis le bocal d’eau.","Ajoute la pierre si tu en as une.","Pose le bocal dehors ou sur un rebord de fenêtre, là où la lune le touche.","Tiens tes mains au-dessus et récite l’incantation, en y mettant l’intention de la lune du mois (voir la table des lunes).","Rentre le bocal avant le lever du soleil, ferme-le et étiquette-le avec la date et le nom de la lune."],
 inc:"Lune pleine, lune d’argent,\nentre dans l’eau doucement.\nQue ta lumière y reste enfermée,\npour mes sorts de l’année.",
 var:["Eau de nouvelle lune : pour les commencements et les intentions.","Eau d’éclipse : très puissante selon la tradition, on la réserve aux grands changements."],
 note:"L’eau de lune apparaît dans presque tous les rituels modernes : on s’en sert pour arroser, purifier les outils, la verser dans un bain ou en asperger une pièce.",
 after:"Utilise-la dans le mois. Si elle devient trouble, verse-la à une plante.",
 warn:"Si tu veux pouvoir la boire, utilise de l’eau potable, un bocal propre, pas de pierre, et garde-la au frais maximum 24 h.",
 m:"Rentre-la avant l’aube."},

{id:"lunenoire",ch:"lune",n:"La lettre de la lune noire",sub:"Trois intentions pour le cycle",lvl:1,moon:"Nouvelle lune",day:"Toutes",dur:"20 min",
 ing:["une bougie noire ou blanche","un papier et une enveloppe","un peu d’eau de lune","un grain de riz ou une graine"],
 steps:["Éteins toutes les lumières. Allume la bougie.","Écris pendant trois minutes sans t’arrêter tout ce qui t’encombre la tête. Déchire la feuille.","Sur une nouvelle feuille, écris trois intentions maximum pour ce cycle, au présent et positives.","Relis-les à voix haute, puis récite l’incantation.","Glisse le papier et la graine dans l’enveloppe, dépose une goutte d’eau de lune sur le rabat et ferme.","Ouvre l’enveloppe à la pleine lune suivante pour voir ce qui a commencé à pousser."],
 inc:"Lune cachée, lune nouvelle,\nje te confie ce qui m’appelle.\nQuand tu reviendras ronde et pleine,\nque ma récolte soit certaine.",
 var:["Tiens un carnet de lunes : une page par cycle."],
 note:"La nouvelle lune n’est pas visible : les Anciens guettaient le premier mince croissant du soir pour commencer le mois. C’est encore le cas des calendriers musulman et juif.",
 after:"Au bout du cycle, brûle la lettre et plante la graine.",
 m:"Trois intentions, pas plus."},

{id:"chargement",ch:"lune",n:"Le chargement des pierres",sub:"Nettoyer et recharger ses cristaux",lvl:1,moon:"Pleine",day:"Toutes",dur:"une nuit",
 ing:["tes pierres et bijoux","un plateau ou un tissu blanc","un bol de sel (pour le nettoyage à sec)","de l’eau (seulement pour les pierres qui la supportent)"],
 steps:["Nettoie d’abord les pierres : rince à l’eau celles qui la supportent (quartz, améthyste, cornaline, agate), pose les autres sur un lit de sel sec sans contact direct, dans un bol posé sur le sel.","Dispose-les sur le tissu blanc, dehors ou sur un rebord de fenêtre, sous la pleine lune.","Passe la main au-dessus d’elles en récitant l’incantation.","Laisse-les toute la nuit. Rentre-les avant que le soleil ne soit fort.","Tiens chaque pierre un instant pour lui redonner une intention."],
 inc:"Pierres de terre, pierres de feu,\nbaignez dans la lune et dans les cieux.\nQue ce qui fut pris soit lavé,\nque votre force soit retrouvée.",
 var:["Au soleil : pour les pierres « solaires » comme la citrine ou la cornaline, mais attention, l’améthyste et le quartz rose pâlissent au soleil."],
 note:"Recharger ses pierres à la lune est une pratique moderne, popularisée par le mouvement New Age dans les années 1980.",
 after:"Aucun reste.",
 warn:"Sélénite, malachite, pyrite, labradorite, turquoise et hématite n’aiment pas l’eau : nettoie-les à sec.",
 m:"Pas d’eau pour la sélénite !"},

{id:"esbatlune",ch:"lune",n:"Faire descendre la lune",sub:"L’invocation de l’esbat",lvl:3,moon:"Pleine",day:"Toutes",dur:"45 min",
 ing:["un endroit où la lune est visible","une bougie argentée ou blanche","un calice d’eau, de vin ou de jus","du pain ou un gâteau"],
 steps:["Trace le cercle complet (voir le chapitre Rituels) et appelle les quatre directions.","Tiens-toi debout face à la lune, les bras levés en forme de croissant, paumes vers le ciel.","Respire lentement et imagine que la lumière de la lune descend en toi par le sommet de la tête et remplit tout ton corps.","Quand tu te sens plein de cette lumière, croise les bras sur ta poitrine et récite l’incantation.","Reste immobile, écoute ce qui vient : une image, un mot, une émotion. Note-le ensuite.","Termine par les gâteaux et le vin : bénis-les, mange et bois, puis verse une part en offrande à la terre.","Ouvre le cercle."],
 inc:"Dame de la nuit aux mille noms,\nArtémis, Séléné, Diane et Hécate,\ndescends en moi comme en ton miroir,\nque je voie avec tes yeux ce soir.",
 var:["En groupe, une personne « reçoit » la lune et parle pour elle : c’est le cœur de l’esbat wiccan traditionnel."],
 note:"Le nom de ce rite vient des sorcières de Thessalie, qui passaient dans la Grèce antique pour savoir faire descendre la lune du ciel. Gerald Gardner en a fait l’un des rites centraux de la Wicca. La journaliste Margot Adler a donné ce titre à son enquête de 1979 sur le paganisme américain.",
 after:"Verse l’offrande au pied d’une plante.",
 m:"Les bras en croissant."},

/* ===================== XII. SCEAUX ===================== */
{id:"sigil",ch:"sceaux",n:"Le sigil",sub:"Transformer une phrase en symbole secret",lvl:2,moon:"Croissante pour attirer, décroissante pour éloigner",day:"Tous",dur:"30 min",
 ing:["un papier et un crayon","une bougie","une coupelle résistante à la chaleur","l’outil interactif « Forge à sigils » plus bas sur ce site"],
 steps:["Écris ton intention au présent et en positif, en majuscules : « JE SUIS SEREIN ».","Barre toutes les voyelles : J S S S R N.","Barre les lettres en double : J S R N.","Assemble les lettres restantes en un seul dessin : superpose-les, fais-les tourner, simplifie-les jusqu’à ce qu’on ne puisse plus les lire.","Charge le sigil : fixe-le en silence en retenant ta respiration, ou en courant, ou dans un moment de forte émotion, jusqu’à ce que ton esprit se vide.","Brûle-le immédiatement et oublie-le. Selon la méthode, c’est l’oubli qui laisse le sigil travailler dans l’inconscient."],
 inc:"(Le sigil se charge en silence. Aucune formule n’est dite.)",
 var:["Dessine un sigil permanent sur un objet (protection de la maison, sous une étagère) au lieu de le brûler.","Méthode de la roue : place l’alphabet sur un cercle et relie les lettres de ton intention par des traits. Essaie-la dans la Forge à sigils."],
 note:"La méthode a été créée par l’artiste et occultiste londonien Austin Osman Spare au début du XXᵉ siècle, dans son livre « The Book of Pleasure » (1913). Les magiciens du chaos l’ont popularisée dans les années 1970, puis elle est devenue l’une des techniques les plus répandues de la sorcellerie moderne.",
 after:"Jette les cendres dehors, au vent.",
 m:"C’est l’oubli qui le fait marcher."},

{id:"sator",ch:"sceaux",n:"Le carré SATOR",sub:"Le plus vieux palindrome magique",lvl:2,moon:"Toutes phases",day:"Samedi",dur:"20 min",
 ing:["un papier de bonne qualité ou une petite plaque de bois","une encre noire ou rouge","une bougie blanche"],
 steps:["Recopie le carré à la main, en capitales, lettre par lettre, sans rature : SATOR / AREPO / TENET / OPERA / ROTAS.","Remarque qu’il se lit dans les quatre sens : de gauche à droite, de droite à gauche, de haut en bas, de bas en haut.","Passe-le au-dessus de la flamme de la bougie sans le brûler, en récitant l’incantation.","Place-le au-dessus d’une porte ou dans un tiroir de la maison pour la protection."],
 inc:"SATOR AREPO TENET OPERA ROTAS,\npar le carré que rien ne défait,\nque cette maison soit gardée en paix.",
 var:["Au Moyen Âge, on gravait le carré sur les linteaux des églises et sur des amulettes contre la fièvre, le feu et les morsures."],
 note:"Le carré SATOR a été retrouvé gravé sur une colonne à Pompéi, donc avant l’éruption de 79 apr. J.-C. Sa signification reste débattue. On le trouve dans toute l’Europe, de l’Angleterre au Portugal, et il a inspiré le titre du film « Tenet ».",
 after:"Il se garde indéfiniment.",
 m:"Se lit dans les quatre sens."},

{id:"pentacle",ch:"sceaux",n:"Le pentacle de protection",sub:"Tracer l’étoile qui garde",lvl:1,moon:"Toutes phases",day:"Samedi",dur:"10 min",
 ing:["ton doigt, une baguette ou un athamé","de l’eau salée ou de l’eau de lune"],
 steps:["Face à la porte ou à la fenêtre à protéger, trempe ton doigt dans l’eau salée.","Trace dans l’air ou sur la surface un pentagramme : en partant de la pointe du haut, descends vers le bas à gauche, remonte vers la droite, traverse vers la gauche, descends vers le bas à droite et remonte au sommet.","C’est le pentagramme « d’invocation de la Terre ». Pour bannir, la tradition le trace en partant du bas à gauche vers le haut.","Entoure-le d’un cercle en tournant dans le sens des aiguilles d’une montre.","Récite l’incantation et touche le centre de l’étoile."],
 inc:"Cinq pointes et un cercle d’or,\nTerre, Air, Feu, Eau, Esprit, dehors comme dedans,\nque rien ne passe sans mon accord,\nici je trace, ici je défends.",
 var:["Trace-le au-dessus de ta tête avant de dormir, ou sur ton sac avant de partir."],
 note:"Le pentagramme était déjà un symbole de protection chez les pythagoriciens. Dans le poème arthurien « Sire Gauvain et le Chevalier vert » (XIVᵉ siècle), il orne le bouclier de Gauvain. La Wicca en a fait son emblème : quatre éléments dominés par l’esprit.",
 after:"Aucun reste.",
 m:"Pointe du haut = esprit."}
]);
