window.CHAPTERS.push({id:"samhain",r:"XIII",n:"Samhain, la nuit des morts",c:"#b0602a",i:"Le 31 octobre, le voile entre les vivants et les morts serait le plus fin de l’année. Ce chapitre rassemble les coutumes de la nuit de Samhain, héritées d’Irlande, d’Écosse et d’Angleterre, dont beaucoup ont donné naissance à Halloween."});

window.SPELLS=window.SPELLS.concat([
{id:"bougiefenetre",ch:"samhain",n:"La bougie à la fenêtre",sub:"Guider les âmes qui rentrent à la maison",lvl:1,moon:"Toutes phases",day:"Nuit du 31 octobre",dur:"Toute la soirée",
 ing:["une bougie blanche ou orange dans un photophore (ou une bougie LED)","une photo d’un proche disparu (facultatif)","un brin de romarin, l’herbe du souvenir"],
 steps:["Au coucher du soleil, choisis la fenêtre qui donne sur la rue ou sur le chemin de la maison.","Pose le photophore sur le rebord, avec le brin de romarin à côté.","Allume la bougie en disant le nom des personnes que tu veux accueillir.","Récite l’incantation.","Laisse la bougie briller jusqu’à ce que tu ailles te coucher. Si tu utilises une vraie flamme, éteins-la avant de dormir."],
 inc:"Petite flamme à ma fenêtre,\nmontre le chemin à ceux qui furent.\nQue les miens reconnaissent ma porte,\net que les autres passent leur route.",
 var:["Une bougie par personne disparue, alignées sur le rebord.","Dans les maisons irlandaises, on laissait aussi la porte entrouverte et une chaise près du feu."],
 note:"Allumer une lumière pour les morts la nuit de Samhain, puis de la Toussaint, est une coutume ancienne d’Irlande et de Bretagne. En Bretagne, on laissait pour les âmes des crêpes et du cidre sur la table la nuit du 1ᵉʳ au 2 novembre.",
 after:"Garde le romarin séché dans ton Livre des Ombres, entre les pages de Samhain.",
 warn:"Ne laisse jamais une flamme près d’un rideau ni sans surveillance. Une bougie LED fait très bien l’affaire.",
 m:"Pour qu’ils retrouvent la maison."},

{id:"repasmuet",ch:"samhain",n:"Le repas muet",sub:"Dîner en silence avec les absents",lvl:2,moon:"Toutes phases",day:"Nuit du 31 octobre",dur:"1 h",
 ing:["une table dressée avec une assiette, un verre et une chaise de plus","une nappe noire ou sombre","une bougie noire et une blanche au centre","les plats préférés des disparus","une petite carte ou un objet pour chaque personne honorée"],
 steps:["Dresse la table normalement, avec une place de plus pour les morts, en bout de table. Pose-y la carte ou l’objet.","Allume les deux bougies. À partir de ce moment, plus personne ne parle.","On sert d’abord l’assiette des morts, avec une petite portion de chaque plat.","Le repas se déroule en silence. Chacun pense aux personnes disparues. On peut écrire un mot sur un papier et le glisser sous l’assiette vide.","À la fin, tout le monde se lève en même temps. Éteins les bougies.","Récite l’incantation : ce sont les premiers mots prononcés depuis le début du repas."],
 inc:"Vous qui étiez à notre table,\nmerci d’être revenus ce soir.\nRepartez en paix vers votre rivage,\nnous vous gardons dans nos mémoires.",
 var:["Version familiale : dix minutes de silence au début du repas suffisent, puis chacun raconte un souvenir.","Certaines traditions servent le repas à l’envers, en commençant par le dessert."],
 note:"Le « dumb supper » est une coutume populaire des îles Britanniques et des Appalaches américaines. À l’origine, c’était souvent une divination : des jeunes filles dînaient à reculons et en silence dans l’espoir de voir apparaître leur futur époux. Les sorcières modernes en ont fait un repas pour honorer les morts.",
 after:"Le lendemain, dépose le contenu de l’assiette des morts dehors, au pied d’un arbre. Les papiers se brûlent.",
 m:"Pas un mot jusqu’à la fin."},

{id:"lanterne",ch:"samhain",n:"La lanterne gardienne",sub:"La citrouille, ou mieux, le navet",lvl:1,moon:"Toutes phases",day:"31 octobre",dur:"1 h",
 ing:["une citrouille, ou un gros navet ou une betterave à l’ancienne","un couteau et une cuillère","une bougie chauffe-plat ou une LED","une pincée de cannelle et de clous de girofle"],
 steps:["Découpe un couvercle, évide la citrouille ou le navet. Garde les graines de citrouille pour les faire griller.","Sculpte un visage effrayant : il doit faire peur aux mauvais esprits, pas aux enfants.","Frotte l’intérieur du couvercle avec la cannelle et les clous de girofle : la chaleur de la bougie diffusera l’odeur.","Pose la lanterne devant la porte, allume la bougie et récite l’incantation.","Laisse-la veiller toute la nuit du 31."],
 inc:"Tête de feu, gardien du seuil,\nfais fuir les ombres de ton œil.\nQue les âmes bienveillantes passent,\net que les méchantes s’effacent.",
 var:["Grave un symbole de protection (pentacle, rune) au lieu d’un visage.","En Écosse, on promenait les lanternes au bout d’un bâton en allant de maison en maison (le « guising »)."],
 note:"En Irlande et en Écosse, on creusait des navets et des betteraves pour en faire des lanternes à visage. Selon la légende, Jack l’Avare, qui avait trompé le diable, fut condamné à errer avec un charbon ardent dans un navet évidé. Les émigrants irlandais ont remplacé le navet par la citrouille américaine, plus facile à creuser : le « jack-o’-lantern » était né.",
 after:"Composte la lanterne au bout de quelques jours, avant qu’elle ne pourrisse. Les graines grillées se mangent.",
 m:"À l’origine : un navet !"},

{id:"sorbier",ch:"samhain",n:"La croix de sorbier",sub:"La protection écossaise de la nuit des morts",lvl:1,moon:"Toutes phases",day:"Veille de Samhain",dur:"20 min",
 ing:["deux petites branches de sorbier des oiseleurs (ou de noisetier), de 10 à 15 cm","du fil rouge","une pincée de sel"],
 steps:["Cueille les branches avec respect, en remerciant l’arbre, sans couteau en métal si possible (on les casse à la main).","Place-les en croix et enroule le fil rouge autour du croisement, neuf fois, en récitant l’incantation.","Noue solidement et passe la croix au-dessus d’une pincée de sel.","Accroche-la au-dessus de la porte d’entrée ou de l’étable, à l’intérieur.","Garde-la jusqu’à la Samhain suivante."],
 inc:"Sorbier rouge et fil de laine,\narrêtez sorcières et peines.\nQue rien de mal ne franchisse\nla porte que je bénis.",
 var:["Ajoute des baies de sorbier enfilées en collier sur un fil rouge.","On en faisait aussi à Beltane, l’autre grande nuit des esprits."],
 note:"Un vieux dicton écossais dit : « Rowan tree and red thread gar the witches tyne their speed », le sorbier et le fil rouge font perdre leur élan aux sorcières. En Écosse et en Irlande, on accrochait des croix de sorbier nouées de rouge aux portes et aux étables à Samhain et à Beltane.",
 after:"L’année suivante, brûle l’ancienne croix dans le feu de Samhain et fais-en une nouvelle.",
 m:"Le sorbier et le fil rouge."},

{id:"noix",ch:"samhain",n:"Les noix dans le feu",sub:"La divination d’amour des nuits d’Halloween écossaises",lvl:1,moon:"Toutes phases",day:"Nuit du 31 octobre",dur:"10 min",
 ing:["deux noix ou deux noisettes","une cheminée, un brasero ou un bol de braises (à défaut, une bougie)"],
 steps:["Prends deux noix. Donne à l’une ton nom, à l’autre celui de la personne à qui tu penses.","Récite l’incantation, puis pose-les côte à côte au bord des braises.","Observe-les sans les quitter des yeux.","Si elles chauffent doucement et brûlent ensemble, le lien sera tranquille et durable. Si l’une éclate ou saute loin de l’autre, le chemin sera agité, ou chacun partira de son côté."],
 inc:"Deux noix au bord du feu,\nnous voilà tous les deux.\nBrûlez ensemble ou sautez,\ndites-moi la vérité.",
 var:["Pour une amitié ou une association : même rituel, mêmes signes.","Sans cheminée : pose les noix sur une plaque résistante à la chaleur, près d’une bougie, et observe si elles se réchauffent au même rythme… c’est surtout un jeu !"],
 note:"En Écosse et dans le Nord de l’Angleterre, la nuit d’Halloween s’appelait parfois « Nutcrack Night », la nuit des noix qui éclatent. Le poète Robert Burns décrit ce jeu dans son poème « Halloween » (1785).",
 after:"Mange les noix qui ont survécu : elles portent chance.",
 warn:"Protège tes yeux : une noix qui éclate peut projeter des éclats brûlants.",
 m:"Si elles sautent… méfiance."},

{id:"miroirpomme",ch:"samhain",n:"Le miroir et la pomme",sub:"Voir son avenir par-dessus son épaule",lvl:2,moon:"Toutes phases",day:"Minuit, nuit du 31 octobre",dur:"15 min",
 ing:["un miroir","une bougie","une pomme rouge","une brosse à cheveux ou un peigne"],
 steps:["Juste avant minuit, éteins toutes les lumières. Allume une seule bougie posée devant le miroir.","Assieds-toi face au miroir, la pomme dans une main, la brosse dans l’autre.","Récite l’incantation à voix basse.","Mange la pomme lentement en te brossant les cheveux, et regarde dans le miroir, sans fixer, au-dessus de ton épaule.","Selon la tradition, le visage de ton futur amour, ou une image de ton avenir, apparaît derrière toi. Ne te retourne pas !","Note ce que tu as vu ou ressenti, même si ce n’est qu’une impression."],
 inc:"Miroir de minuit, miroir d’argent,\nmontre-moi ce qui m’attend.\nPar la pomme et par la flamme,\nque l’avenir soit sans drame.",
 var:["Version sans amour : pose une question sur l’année qui vient et laisse venir les images.","C’est une forme de miroir noir : les techniques du chapitre Divination s’appliquent."],
 note:"Burns mentionne aussi cette coutume dans « Halloween » : manger une pomme devant le miroir à minuit pour voir apparaître son futur époux. Les cartes postales d’Halloween du début du XXᵉ siècle représentent souvent des jeunes femmes devant un miroir, une bougie à la main.",
 after:"Plante un pépin de la pomme dans un pot : s’il germe, l’année sera heureuse.",
 m:"Ne te retourne pas !"},

{id:"painames",ch:"samhain",n:"Le pain des âmes",sub:"Des gâteaux offerts pour les morts",lvl:1,moon:"Toutes phases",day:"31 octobre – 2 novembre",dur:"1 h 30",
 ing:["250 g de farine","100 g de beurre mou","80 g de sucre","1 œuf","1 cuillère à café de cannelle, muscade et piment de la Jamaïque (ou quatre-épices)","une poignée de raisins secs","un peu de lait"],
 steps:["Mélange la farine, le sucre et les épices. Ajoute le beurre et travaille du bout des doigts pour obtenir un sable.","Ajoute l’œuf, les raisins et juste assez de lait pour former une pâte souple.","Étale la pâte sur 1 cm d’épaisseur et découpe des disques de 7 cm.","Avec un couteau, trace une croix sur chaque gâteau (ou un pentacle, ou un soleil).","Fais cuire 15 minutes à 180 °C.","Pose le premier gâteau sur l’autel des ancêtres en récitant l’incantation, puis partage les autres avec tes proches ou tes voisins."],
 inc:"Un gâteau pour l’âme qui passe,\nun gâteau pour celle qui reste.\nQue les morts trouvent leur place,\net les vivants une fête.",
 var:["Offre-les aux enfants qui passent pour Halloween : c’est exactement le sens de la tradition.","Sans gluten : farine de riz et de sarrasin, moitié-moitié."],
 note:"En Angleterre, jusqu’au XIXᵉ siècle, les pauvres et les enfants allaient de porte en porte à la Toussaint et au jour des morts pour réclamer des « soul cakes ». En échange, ils promettaient de prier pour les défunts de la maison. Cette coutume, le « souling », est l’un des ancêtres du « trick or treat ».",
 after:"Le gâteau de l’autel est déposé dehors le 2 novembre, pour les oiseaux.",
 m:"L’ancêtre du « bonbon ou un sort »."},

{id:"chaudronadieux",ch:"samhain",n:"Le chaudron des adieux",sub:"Brûler l’année qui s’achève",lvl:2,moon:"Toutes phases",day:"Nuit du 31 octobre",dur:"45 min",
 ing:["un chaudron ou une cocotte en fonte, avec un fond de sable","des petits papiers et un crayon","des feuilles mortes ramassées dans la journée","une bougie noire","du romarin ou de la sauge officinale séchée"],
 steps:["Trace le cercle et allume la bougie noire à côté du chaudron.","Sur chaque feuille morte, ou sur chaque papier, écris une chose que tu veux laisser mourir avec l’année celtique : une peur, une habitude, une rancune, une relation terminée.","Lis chaque papier à voix haute, puis enflamme-le à la bougie et laisse-le tomber dans le chaudron.","Quand tout a brûlé, ajoute le romarin sur les braises pour purifier.","Récite l’incantation.","Ouvre le cercle. Au réveil, le 1ᵉʳ novembre, écris trois graines pour l’année nouvelle."],
 inc:"L’année meurt, le voile est mince,\nje te rends ce qui me pince.\nQue le feu mange ce qui fut,\nqu’à Yule renaisse ce qui n’est plus.",
 var:["Seul ou en groupe : en groupe, chacun lance ses papiers en silence.","Sans feu : déchire les papiers et enterre-les avec les feuilles mortes."],
 note:"Pour les Celtes, Samhain marquait la fin de l’année et le début de la saison sombre. Les grands feux allumés sur les collines, notamment sur la colline de Tlachtga en Irlande, servaient à rallumer les foyers de toute la région. La sorcellerie moderne en a fait la nuit où l’on laisse partir ce qui doit finir.",
 after:"Enterre les cendres refroidies au pied d’un arbre. Elles nourriront le printemps.",
 warn:"Fais-le dehors ou près d’une fenêtre ouverte, sur une surface qui ne craint pas la chaleur, avec un verre d’eau à portée de main.",
 m:"Ce qui meurt ce soir renaîtra."}
]);
